[[a3210]]
== Exception Handling

This chapter defines requirements for
exception handling of entity beans and JAX-RPC web service endpoints in
addition to the contracts specified in the EJB Core Contracts and
Requirements document link:Ejb.html#a3339[See EJB 3.2 Core
Contracts and Requirements. http://jcp.org/en/jsr/detail?id=345] Chapter
“Exception Handling”.

=== Application Exceptions



The
javax.ejb.CreateException,
javax.ejb.RemoveException,
javax.ejb.FinderException, and subclasses
thereof are application exceptions used to report errors to the client
from the create, remove, and finder methods of the EJBHome and/or
EJBLocalHome interfaces of entity bean components (see Subsections
link:Ejb.html#a1524[See Standard Application Exceptions for
Entities] and link:Ejb.html#a2806[See Standard Application
Exceptions for Entities]). See rules for the application exceptions
defined in the corresponding section of the EJB Core Contracts and
Requirements document link:Ejb.html#a3339[See EJB 3.2 Core
Contracts and Requirements. http://jcp.org/en/jsr/detail?id=345].

=== Bean Provider’s Responsibilities



This section defines the responsibilities of
the Bean Provider for exception handling of entity beans in addition to
the Bean Provider’s responsibilities specified in the corresponding
section in the EJB Core Contracts and Requirements document
[link:Ejb.html#a3339[See EJB 3.2 Core Contracts and
Requirements. http://jcp.org/en/jsr/detail?id=345]].

=== Application Exceptions

The Bean Provider is responsible for using
the standard EJB application exceptions (javax.ejb.CreateException,
javax.ejb.RemoveException, javax.ejb.FinderException, and subclasses
thereof) for entity beans as described in Subsections
link:Ejb.html#a1524[See Standard Application Exceptions for
Entities] and link:Ejb.html#a2806[See Standard Application
Exceptions for Entities].

=== [[a3221]]System Exceptions

The Bean Provider should handle various
system-level exceptions and errors that an entity bean instance may
encounter during the execution of a business method (e.g. ejbLoad).

=== javax.ejb.NoSuchEntityException

The
NoSuchEntityException is a subclass of
EJBException. It should be thrown by the entity bean class methods to
indicate that the underlying entity has been removed from the database.

A bean-managed
persistence entity bean class typically throws this exception from the
ejbLoad and ejbStore methods, and from the methods that implement the
business methods defined in the component interface.

=== [[a3227]]Container Provider Responsibilities



This section defines the responsibilities of
the Container Provider for exception handling of entity beans in
addition to the Container Provider’s responsibilities specified in the
corresponding section in the EJB Core Contracts and Requirements
document [link:Ejb.html#a3339[See EJB 3.2 Core Contracts and
Requirements. http://jcp.org/en/jsr/detail?id=345]].

=== [[a3229]]Exceptions from Method Invoked via Entity Bean’s Client View

The following entity bean methods:
ejbCreate<METHOD>, ejbPostCreate<METHOD>, ejbRemove, _ejbHome<METHOD>_ ,
and ejbFind<METHOD> are considered to be business methods in this
context.

Rules for exception handling of these methods
are specified in the Table “Handling of Exceptions Thrown by Methods of
Web Service Client View or EJB 2.1 Client View of a Bean with
Container-Managed Transaction Demarcation” of the EJB Core Contracts and
Requirements document [link:Ejb.html#a3339[See EJB 3.2 Core
Contracts and Requirements. http://jcp.org/en/jsr/detail?id=345]].

=== [[a3232]]Exceptions from Other Container-invoked Callbacks

This subsection applies to the ejbActivate,
ejbLoad, ejbPassivate, ejbStore, setEntityContext, and
unsetEntityContext container-invoked callbacks methods of the EntityBean
interface.

The container must handle all exceptions or
errors from these methods as follows:

Log the exception or error to bring the
problem to the attention of the System Administrator.

If the instance is in a transaction, mark the
transaction for rollback.

Discard the instance (i.e., the container
must not invoke any business methods or container callbacks on the
instance).

If the exception or error happened during the
processing of a client invoked method, throw the
_javax.ejb.EJBExceptionlink:#a3395[31]_ . If the EJB 2.1 client
view or web service client view is used, throw the
java.rmi.RemoteException to the client if the client is a remote client
or throw the _javax.ejb.EJBException_ to the client if the client is a
local client. If the instance executed in the client’s transaction, the
container should throw the
_javax.ejb.EJBTransactionRolledbackExceptionlink:#a3396[32]_ .
If the EJB 2.1 client view or web service client view is used, the
container should throw the
javax.transaction.TransactionRolledbackException to a remote client or
the _javax.ejb.TransactionRolledbackLocalException_ to a local client,
because it provides more information to the client. (The client knows
that it is fruitless to continue the transaction.)

=== javax.ejb.NoSuchEntityException

The
NoSuchEntityException is a subclass of
EJBException. If it is thrown by a method of an entity bean class, the
container must handle the exception using the rules in Sections
link:Ejb.html#a3229[See Exceptions from Method Invoked via
Entity Bean’s Client View] and link:Ejb.html#a3232[See
Exceptions from Other Container-invoked Callbacks].

To give the client a better indication of the
cause of the error, the container should throw the
java.rmi.NoSuchObjectException (which is a subclass of
java.rmi.RemoteException) to a remote client, or the
_javax.ejb.NoSuchObjectLocalException_ to a local client.

=== Non-existing Entity Object

If a client makes a call to an entity object
that has been removed, the container should throw the
_javax.ejb.NoSuchEJBExceptionlink:#a3397[33]_ . If the EJB 2.1
client view is used, the container should throw the
java.rmi.NoSuchObjectException (which is a
subclass of java.rmi.RemoteException) to a remote client, or the
_javax.ejb.NoSuchObjectLocalException_ to a local client.

=== Support for Deprecated Use of java.rmi.RemoteException

The EJB 1.0
specification allowed the business methods, ejbCreate, ejbPostCreate,
ejbFind<METHOD>, ejbRemove, and the container-invoked callbacks (i.e.,
the methods defined in the EntityBean interface) implemented in the
enterprise bean class to use the java.rmi.RemoteException to report
non-application exceptions to the container.

See the corresponding section in the EJB Core
Contracts and Requirements document [link:Ejb.html#a3339[See EJB
3.2 Core Contracts and Requirements.
http://jcp.org/en/jsr/detail?id=345]] for the rules on support of the
deprecated use of java.rmi.RemoteException.

=== Client’s View of Exceptions



The JAX-RPC web service endpoint interface is
Java RMI interface, and therefore the _throws_ clauses of all its
methods (including those inherited from superinterfaces) include the
mandatory java.rmi.RemoteException.The
_throws_ clauses may include an arbitrary number of application
exceptions.

See the corresponding section in the EJB Core
Contracts and Requirements document [link:Ejb.html#a3339[See EJB
3.2 Core Contracts and Requirements.
http://jcp.org/en/jsr/detail?id=345]] for the client’s view of
exceptions received from from enterprise beans and web service
endpoints.
