== Introduction

This document describes features for which support has been made optional as of the 3.2 release of the Enterprise Beans specification:

* _Enterprise Beans 2.1 Entity Bean Component Contract for Container-Managed Persistence_
* _Enterprise Beans 2.1 Entity Bean Component Contract for Bean-Managed Persistence_
* _Enterprise Beans 1.1 Entity Bean Component Contract for Container-Managed Persistence_
* _Client View of an Entity Bean_
* _Enterprise Beans QL: Query Language for Container-Managed Persistence Query Methods_
* _Jakarta XML RPC Based Web Service Endpoints_
* _Jakarta XML RPC Web Service Client View._

=== Acknowledgements

The Enterprise Beans 3.2 specification work was conducted as part of JSR-345 under the Java Community Process Program.
This specification is the result of the collaborative work of the members of the EJB 3.2 Expert Group: Caucho Technology, Inc: Reza Rahman; IBM: Jeremy Bauer; Oracle: Marina Vatkina, Linda DeMichiel; OW2: Florent Benoit; Pramati Technologies: Ravikiran Noothi; RedHat: Pete Muir, Carlo de Wolf; TmaxSoft, Inc.: Miju Byon; individual members: Adam Bien; David Blevins; Antonio Goncalves; Stefan Heldt; Richard Hightower, Jean-Louis Monteiro.

=== Organization of the Specification Documents

This specification is organized into the following documents:

* Enterprise Beans Core Contracts and Requirements
* Enterprise Beans Optional Features

The Enterprise Beans Core Contracts and Requirements document defines the contracts and requirements for the use and implementation of Enterprise Beans. 
These contracts include those for the Enterprise Beans 3.2 API, as well as for the earlier Enterprise Beans API that is required to be supported in this release.

This Enterprise Beans Optional Features document defines the contracts and requirements for the use and implementation of features support for which has been made optional for the Enterprise Beans. 
These contracts are separated from the core contracts requirements in the Enterprise Beans 3.1 specification <<a3323>>.

=== Document Conventions

The regular font is used for information that is prescriptive by the Enterprise Beans specification.

_The italic font is used for paragraphs that contain descriptive information, such as notes describing typical use, or notes clarifying the text with prescriptive specification._

`The monospace font is used for code examples.`
