== Overview

This document describes features for which support has been made optional as of the 3.2 release of the Enterprise Beans specification:

* _Enterprise Beans 2.1 Entity Bean Component Contract for Container-Managed Persistence_
* _Enterprise Beans 2.1 Entity Bean Component Contract for Bean-Managed Persistence_
* _Enterprise Beans 1.1 Entity Bean Component Contract for Container-Managed Persistence_
* _Client View of an Entity Bean_
* _Enterprise Beans QL: Query Language for Container-Managed Persistence Query Methods_

If an implementation supports such features, it must do so in accordance with the requirements of this specification.
In addition, the following rules apply:

* If any of the following features is supported, all features in the list must be supported:
** Enterprise Beans 2.x entity beans with container-managed persistence
** Enterprise Beans 1.1 entity beans with container-managed persistence
** Enterprise Beans 2.x entity beans with bean-managed persistence
** Enterprise Beans QL

See the general description of the Enterprise Beans goals and requirements in the Enterprise Beans Core Contracts and Requirements <<a3339>> document.
