[[a3185]]
== Support for Transactions

=== Overview



This chapter defines requirements for
transaction support of entity beans in addition to the contracts
specified in the EJB Core Contracts and Requirements document
link:Ejb.html#a3339[See EJB 3.2 Core Contracts and Requirements.
http://jcp.org/en/jsr/detail?id=345] Chapter “Support for Transactions”.

=== Bean Provider’s Responsibilities



This section defines the responsibilities of
the Bean Provider for transaction demarcation in entity beans. See the
corresponding section in the EJB Core Contracts and Requirements
document [link:Ejb.html#a3339[See EJB 3.2 Core Contracts and
Requirements. http://jcp.org/en/jsr/detail?id=345]] for the complete
description of the Bean Provider responsibilities.

==== Bean-Managed Versus Container-Managed Transaction Demarcation

An entity bean
must always use container-managed transaction demarcation. An entity
bean must not be designated with bean-managed transaction demarcation.

==== Isolation Levels

The isolation
level describes the degree to which the access to a resource manager by
a transaction is isolated from the access to the resource manager by
other concurrently executing transactions.

The following are guidelines for managing
isolation levels in entity beans:

The Container Provider should insure that
suitable isolation levels are provided to guarantee data consistency for
entity beans. Typically this means that an equivalent of a repeatable
read or serializable isolation level should be available for
applications that require a high degree of isolation.

For entity beans with container-managed
persistence, transaction isolation is managed by the data access classes
that are generated by the Container Provider’s tools. The tools must
ensure that the management of the isolation levels performed by the data
access classes will not result in conflicting isolation level requests
for a resource manager within a transaction.

==== Specification of the Transaction Attributes for a Bean’s Methods

The Bean Provider
of an enterprise bean with container-managed transaction demarcation may
specify the transaction attributes for the enterprise bean’s methods.

A transaction attribute is a value associated
with a method of an entity bean’s home or component interface.

{empty}The transaction attributes are
specified for the methods defined in the bean’s component interface and
all the direct and indirect superinterfaces of the component interface,
excluding the getEJBHome, _getEJBLocalHome_ , getHandle, getPrimaryKey,
and isIdentical methods; for the methods defined in the bean’s home
interface and all the direct and indirect superinterfaces of the home
interface, excluding the getEJBMetaData and getHomeHandle methods
specific to the remote home interface; and for the timeout callback
methods, if any.link:#a3394[30]

For entity beans that use container-managed
persistence, only the _Required_ , _RequiresNew_ , or _Mandatory_
deployment descriptor transaction attribute values should be used for
the methods defined in the bean’s component interface and all the direct
and indirect superinterfaces of the component interface, excluding the
getEJBHome, _getEJBLocalHome_ , getHandle, getPrimaryKey, and
isIdentical methods; and for the methods defined in the bean’s home
interface and all the direct and indirect superinterfaces of the home
interface, excluding the getEJBMetaData and getHomeHandle methods
specific to the remote home interface.

The Bean Provider and Application Assembler
must exercise caution when using the _RequiresNew_ transaction
attributes with the navigation of container-managed relationships. If
higher levels of isolation are used, navigating a container-managed
relationship in a new transaction context may result in deadlock.

Containers may _optionally_ support the use
of the _NotSupported_ , _Supports_ , and _Never_ transaction attributes
for the methods of entity beans with container-managed persistence.
However, entity beans with container-managed persistence that use these
transaction attributes will not be portable.

Containers may optionally support the use of
the _NotSupported_ , _Supports_ , and _Never_ transaction attributes for
the methods of entity beans with container-managed persistence because
the use of these transaction modes may be needed to make use of
container-managed persistence with non-transactional data stores. In
general, however, the Bean Provider and Application Assembler should
avoid use _of the NotSupported_ _,_ _Supports_ , _and_ _Never_
_transaction attribute values for the methods of entity beans with
container-managed persistence because it may lead to inconsistent
results or to the inconsistent and/or to the partial updating of
persistent state and relationships in the event of concurrent use_ .

=== Container Provider Responsibilities



This section defines the responsibilities of
the Container Provider for transaction demarcation in entity beans. See
the EJB Core Contracts and Requirements document
[link:Ejb.html#a3339[See EJB 3.2 Core Contracts and
Requirements. http://jcp.org/en/jsr/detail?id=345]] for the complete
description of the Container Provider responsibilities.

==== Container-Managed Transaction Demarcation for Entity Beans

The container is responsible for providing
the transaction demarcation for the entity beans with bean-managed
persistence and container-managed persistence.

The container must demarcate transactions as
specified by the transaction attribute values specified in the
deployment descriptor. See subsections of “Container-Managed Transaction
Demarcation for Business Methods” of the EJB Core Contracts and
Requirements document link:Ejb.html#a3339[See EJB 3.2 Core
Contracts and Requirements. http://jcp.org/en/jsr/detail?id=345] for the
available options and detailed description of the responsibilities of
the Container Provider.
