[[a3139]]
== Support for Jakarta XML RPC Web Service Endpoints

A stateless session bean may implement a Jakarta XML RPC web service endpoint.
XML RPC web service endpoints are accessed by Java clients through the XML RPC client APIs, which utilize an XML-based protocol (SOAP 1.2 <<a3338>>) over an HTTP transport.

A XML RPC web service client makes use of the enterprise bean’s XML RPC web service client view corresponding to the web service endpoint interface, as described by a WSDL document.

This chapter defines requirements for stateless sessions beans and Enterprise Beans containers that support XML RPC web service endpoints.
See Enterprise Beans Core Contracts and Requirements document <<a3339>> for additional requirements that apply to stateless session beans.

=== XML RPC Web Service Client View

The XML RPC web service client obtains a reference to the service object that implements the `javax.xml.rpc.Service` interface through dependency injection or using JNDI.
The service interface can be a generic `javax.xml.rpc.Service` interface or a generated service interface which extends the `javax.xml.rpc.Service` interface.
The service interface is then used to obtain a stub or proxy that implements the session bean’s web service endpoint interface.
The mechanisms and APIs for client web service access is described in the Jakarta XML RPC specification <<a3332>>.

The following example illustrates how a Jakarta EE client looks up a web service in JNDI using a logical name called a service reference (specified using the `service-ref` element), obtains a stub instance for a web service endpoint, and invokes a method on that endpoint.
[source, java]
----
Context ctx = new InitialContext();

com.example.StockQuoteService sqs = (com.example.StockQuoteService)
        ctx.lookup("java:comp/env/service/StockQuoteService");
com.example.StockQuoteProvider sqp = sqs.getStockQuoteProviderPort();
float quotePrice = sqp.getLastTradePrice("ACME");
...
----

The use of service references and the `service-ref` deployment descriptor element are described in further detail in <<a3337>>.

=== The Responsibilities of the Bean Provider

This section describes the responsibilities of the session Bean Provider to support XML RPC web service endpoints.
These requirements are in addition to those specified in the Enterprise Core Contracts and Requirements document <<a3339>>.

==== Session Bean’s JAX-RPC Service Endpoint Interface

The following are the requirements for stateless session beans with XML RPC web service endpoint interfaces.

* The interface must follow the rules for XML RPC service endpoint interfaces <<a3332>>.

* The interface must extend the `java.rmi.Remote` interface.

* The methods defined in the interface must follow the rules for XML RPC service endpoint interfaces.
This means that their argument and return values must be of valid types for XML RPC, and their `throws` clauses must include the `java.rmi.RemoteException`.
The `throws` clause may additionally include application exceptions.
+
_Note that XML RPC Holder classes may be used as method parameters.
The Jakarta XML RPC specification requires support for Holder classes as part of the standard Java mapping of WSDL operations in order to handle out and inout parameters.
Holder classes implement the `javax.xml.rpc.holders.Holder` interface.
See the Jakarta XML RPC specification <<a3332>> for further details._

* For each method defined in the web service endpoint interface, there must be a matching method in the session bean’s class.
The matching method must have:

** The same name.

** The same number and types of arguments, and the same return type.

** All the exceptions defined in the `throws` clause of the matching method of the session bean class must be defined in the `throws` clause of the method of the web service endpoint interface.

* The web service endpoint interface must not include an EJBObject or EJBLocalObject as either a parameter or return type.
An array or XML RPC value type must not include an EJBObject or EJBLocalObject as a contained element.
The web service endpoint interface methods must not expose business interface types, local or remote component interface types, local or remote home interface types, timers or timer handles, or the managed collection classes that are used for entity beans with container-managed persistence as arguments or results or as fields of value types.

* XML RPC serialization rules apply for any value types that are used by the web service endpoint interface.
If it is important that Java serialization semantics apply, the Bean Provider should use the restricted set of XML RPC value types for which the semantics of Java serialization apply under XML RPC serialization.
See the Jakarta XML RPC specification <<a3332>> for details.

* The web service endpoint interface must not include constant (as `public final static`) declarations.

The Bean Provider must designate the web service endpoint interface in the deployment descriptor by means of the `service-endpoint` element.
The service endpoint itself is only exposed within a web service if it is referenced by a web service deployment descriptor as defined by <<a3337>>.

==== MessageContext Interface

The `MessageContext` interface allows the stateless session bean instance to see the SOAP message for the web service endpoint, as well as the properties set by the XML RPC SOAP message handlers, if any.
The stateless session bean may use the `MessageContext` interface to set properties for XML RPC message response handlers.

A stateless session bean that implements a web service endpoint using the XML RPC contracts accesses the XML RPC `MessageContext` interface by means of the `SessionContext.getMessageContext` method.
The `getMessageContext` method returns the `javax.xml.rpc.handler.MessageContext` interface of a stateless session bean that implements a XML RPC web service endpoint.

Only stateless session beans with web service endpoint interfaces are permitted to use this method.

=== The Responsibilities of the Container Provider

This section describes the responsibilities of the Container Provider to support XML RPC web service endpoints.
These requirements are in addition to those specified in the Enterprise Beans Core Contracts and Requirements document <<a3339>>.

==== Generation of WSDL

Reference <<a3337>> describes the generation of a WSDL document for a web service endpoint.
The Java to WSDL mapping must adhere to the requirements of Jakarta XML RPC specification <<a3332>>.

==== JAX-RPC Message Handlers for Web Service Endpoints

The container must support the use of XML RPC message handlers for web service endpoints.
Container requirements for support of message handlers are specified in <<a3337>>.

If message handlers are present, they must be invoked before any business method interceptor methods.

==== The SessionContext Interface Restrictions

Invoking the `getMessageContext` method of the `SessionContext` interface is disallowed in session bean methods that were not invoked by the container through the session bean’s web service endpoint.
