[[a3258]]
== Timer Service

This chapter defines limitations of the Enterprise Beans container-managed timer service when used with Enterprise Beans 2.1 entity beans.

=== Bean Provider’s View of the Timer Service

Timers can be created for Enterprise Beans 2.1 entity beans.
A timer that is created for the Enterprise Beans 2.1 entity bean is associated with the entity bean’s identity.

Use of the Enterprise Beans Timer Service is not supported for an Enterprise Beans 1.1 entity bean with container-managed persistence.

==== Calendar-Based Time Expressions

Calendar based timers are not supported for entity beans.

==== Non-persistent Timers

Non-persistent timers are not supported for entity beans.

==== The TimerService Interface

For an Enterprise Beans 2.1 entity bean, the result of `getTimers` is a collection of those timers that are associated with the bean’s identity.

==== Timer Expiration and Timeout Callback Method

If a timer for an Enterprise Beans 2.1 entity bean expires, and the bean has been passivated, the container must call the `ejbActivate` and `ejbLoad` methods on the entity bean class before calling the timeout callback method, as described in <<a1279>> and <<a2553>>.

==== Entity Bean Removal

If an entity bean is removed, the container must remove the timers for that bean.
