[[a2004]]
== Interceptors

Interceptors are used to interpose on the
business method invocations and lifecycle events that occur on an
enterprise bean instance.

=== Overview

The general rules for defining Interceptor
classes, their lifecycle, and associated metadata are described in the
_Jakarta Interceptors_ specification <<a9887>>. This
chapter describes the set of requirements that are specific to the use
of interceptors with Enterprise Beans.

For the use of interceptors with Enterprise
Beans, the interceptor "target class" is the bean class.
Interceptors may be used with session beans and message-driven beans.

The programming restrictions that apply to
enterprise bean components apply to interceptors as well. See <<a9535>>.

It is illegal to associate Jakarta Transactions
transactional interceptors (see <<a9857>>) with Enterprise Beans. The
Enterprise Beans Container should fail deployment of such
applications.footnote:a10261[This restriction may be removed in a future 
release of this specification.]

Default interceptors are interceptors that
apply to all components within an ejb-jar file or `.war` file.

=== Interceptor Life Cycle

The lifecycle of an interceptor instance is
the same as that of the bean instance with which it is associated. In
the case of interceptors associated with stateful session beans, the
interceptor instances are passivated upon bean instance passivation, and
activated when the bean instance is activated. See 
<<a921>>, <<a1077>>, and <<a1871>>.

In addition to the `AroundConstruct`,
`PostConstruct` and `PreDestroy` callback support required by the
_Jakarta Interceptors_ specification <<a9887>>,
interceptors associated with stateful session beans may define
`PostActivate` and `PrePassivate` callbacks. Both the interceptor instance
and the bean instance are created or activated before any of the
respective `PostConstruct` or `PostActivate` callbacks are invoked. Any
`PreDestroy` and `PrePassivate` callbacks are invoked before the
respective destruction or passivation of either the bean instance or
interceptor instance.

The use of an extended persistence context is
only supported for interceptors that are associated with stateful
session beans.

=== Business Method Interceptors

`AroundInvoke` interceptor methods may be
defined for business methods of sessions beans and for the message
listener methods of message-driven beans.

Business method interceptor methods may throw
runtime exceptions or application exceptions that are allowed in the
`throws` clause of the business method. See section
<<a2031>> for further details.

=== Timer Timeout Method Interceptors

Interceptor methods may be defined for the
Enterprise Beans timer timeout methods of session beans and message-driven beans.
Such methods are referred to as `AroundTimeout` methods.

Within an `AroundTimeout` method, the
`InvocationContext.getTimer()` method returns the `javax.ejb.Timer`
object associated with the timeout being intercepted.

`AroundTimeout` methods may throw system exceptions, but not 
application exceptions. See <<a2031>> for further details.

[[a2023]]
=== Interceptors for LifeCycle Event Callbacks

Lifecycle callback interceptor methods may be
defined for session beans and message-driven beans.

The `AroundConstruct`, `PostConstruct`,
`PreDestroy`, `PostActivate`, and `PrePassivate` annotations are used
to define interceptor methods for a lifecycle callback events. An
`AroundConstruct` lifecycle callback interceptor method may be defined on
an interceptor class only. All other interceptor methods can be defined
on an interceptor class and/or directly on the bean class.

Lifecycle callback interceptor methods are
invoked in an unspecified security context. Lifecycle callback
interceptor methods are invoked in an unspecified transaction context,
except for singleton and stateful session bean `PostConstruct` and
`PreDestroy` methods and stateful session bean `PostActivate`, and
`PrePassivate` methods, whose transaction context is based on their
respective transaction attributes. See <<a705>>.

`PostActivate`, and `PrePassivate` methods
follow requirements for the lifecycle callback interceptor methods
defined in the Interceptors specification document <<a9887>>.

Lifecycle callback interceptor methods may 
throw system runtime exceptions, but not application exceptions. See
<<a2031>> for further details.

[[a2029]]
=== InvocationContext

The `InvocationContext` object provides
metadata that enables interceptor methods to control the behavior of the
invocation chain. The `getContextData` method enables an interceptor to
retrieve or update the data associated with the invocation by another
interceptor, business method, and/or webservices context in the
invocation chain. The contextual data is not sharable across separate
business method invocations or lifecycle callback events. If
interceptors are invoked as a result of the invocation on a web service
endpoint, the map returned by the `getContextData` method will be the
Jakarta XML Web Services `MessageContext` <<a9881>>. The lifecycle of the
`InvocationContext` instance is otherwise unspecified.

[[a2031]]
=== Exception Handling

Interceptor methods are allowed to throw
runtime exceptions or any checked exceptions that the method they
interpose on allows within its `throws` clause. Interceptor methods
are allowed to catch and suppress exceptions and recover by calling
`proceed()`.

Interceptor method invoked in a
transaction context, can mark the transaction for rollback by throwing a
runtime exception or by calling the `EJBContext` method
`setRollbackOnly()`. This may be done before or after
`InvocationContext.proceed()` is called.

If a system exception escapes the interceptor
chain, the bean instance and any associated interceptor instances are
discarded (unless the bean is a singleton session
bean footnote:a10262[See <<a1254>>]). The `PreDestroy` callbacks are not invoked
in this case: the interceptor methods in the chain should perform any
necessary clean-up operations as the interceptor chain unwinds.

=== Specification of Interceptors in the Deployment Descriptor

The deployment descriptor can be used as an
alternative to metadata annotations to specify interceptors and their
binding to enterprise beans or to override the invocation order of
interceptors as specified in annotations.

==== Specification of Interceptors

The `interceptor` deployment descriptor
element is used to specify the interceptor methods of an interceptor
class. The interceptor methods are specified by using the
`around-invoke`, `around-timeout`, `around-construct`,
`post-construct`, `pre-destroy`, `pre-passivate`, and `post-activate`
elements.

At most one method of a given interceptor
class can be designated as an around-invoke method, an around-timeout
method, a lifecycle callback interceptor method, regardless of whether
the deployment descriptor is used to define interceptors or whether some
combination of annotations and deployment descriptor elements is used.

==== Binding of Interceptors to Target Classes

The `interceptor-binding` element is used to
specify the binding of interceptor classes to target classes and their
methods. The subelements of the `interceptor-binding` element are as
follows:

* The `target-name` element must identify the
associated target class or the wildcard value `"*"` (which is used to
define interceptors that are bound to all target classes).

* The `interceptor-class` element specifies the
interceptor class. The interceptor class contained in an
`interceptor-class` element must either be declared in the `interceptor`
deployment descriptor element or appear in at least one `Interceptor`
annotation on a target class. The `interceptor-order` element is used as
an optional alternative to specify a total ordering over the
interceptors defined for the given level and above.

* The `exclude-default-interceptors` and
`exclude-class-interceptors` elements specify that default interceptors
and class interceptors, respectively, are not to be applied to a target
class and/or method.

* The `method-name` element specifies the
method name for a method-level interceptor; and the optional
`method-params` elements identify a single method among multiple methods
with an overloaded method name.

* The `method-name` element may be used to bind
a constructor-level interceptor using the unqualified name of the bean
class as the value; the optional `method-params` elements identify the
constructor if a bean class has a constructor annotated with the `Inject`
annotation in addition to a no-arg constructor.

Default interceptors are bound to all target
classes in a module using the wildcard syntax `"*"`. In addition,
interceptors may be bound at the level of the target class (class-level
interceptors) or methods of the target class (method-level
interceptors).

The binding of interceptors to classes is
additive. If interceptors are bound at the class level and/or default
level as well as at the method level, both class-level and/or
default-level as well as method-level interceptors will apply. The
deployment descriptor may be used to augment the interceptors and
interceptor methods defined by means of annotations. When the deployment
descriptor is used to augment the interceptors specified in annotations,
the interceptor methods specified in the deployment descriptor will be
invoked after those specified in annotations, according to the ordering
specified earlier. The `interceptor-order` deployment descriptor element
may be used to override this ordering.

The `exclude-default-interceptors` element
disables default interceptors for the level at which it is specified and
lower. That is, `exclude-default-interceptors` when applied at the class
level disables the application of default interceptors for all methods
of the class. The `exclude-class-interceptors` element applied to a
method disables the application of class-level interceptors for the
given method. Explicitly listing an excluded higher-level interceptor at
a lower level causes it to be applied at that level and below.

It is possible to override the ordering of
interceptors by using the `interceptor-order` element to specify a total
ordering of interceptors at class level and/or method level. If the
`interceptor-order` element is used, the ordering specified at the given
level must be a total order over all interceptor classes that have been
defined at that level and above (unless they have been explicitly
excluded by means of one of the `exclude-` elements described above).

There are four possible styles of the
`interceptor-binding` element syntax:

*Style 1:*
[source, xml]
----
<interceptor-binding>
    <target-name>*</target-name>
    <interceptor-class>INTERCEPTOR</interceptor-class>
</interceptor-binding>
----

Specifying the `target-name` element as the
wildcard value `"*"` designates default interceptors.

*Style 2:*
[source, xml]
----
<interceptor-binding>
    <target-name>TARGETNAME</target-name>
    <interceptor-class>INTERCEPTOR</interceptor-class>
</interceptor-binding>
----

This style is used to refer to interceptors
associated with the specified target class (class-level interceptors).

*Style 3:*
[source, xml]
----
<interceptor-binding>
    <target-name>TARGETNAME</target-name>
    <interceptor-class>INTERCEPTOR</interceptor-class>
    <method-name>METHOD</method-name>
</interceptor-binding>
----

This style is used to associate a
method-level interceptor with the specified method of the specified
target class. If there are multiple methods with the same overloaded
name, the element of this style refers to all the methods with the
overloaded name. Note that the wildcard value `"*"` cannot be used to
specify method-level interceptors.

*Style 4:*
[source, xml]
----
<interceptor-binding>
    <target-name>TARGETNAME</target-name>
    <interceptor-class>INTERCEPTOR</interceptor-class>
    <method-name>METHOD</method-name>
    <method-params>
        <method-param>PARAM-1</method-param>
        <method-param>PARAM-2</method-param>
        ...
        <method-param>PARAM-n</method-param>
    </method-params>
<interceptor-binding>
----

This style is used to associate a
method-level interceptor with the specified method of the specified
target class. This style is used to refer to a single method within a
set of methods with an overloaded name. The values `PARAM-1` through
`PARAM-n` are the fully-qualified Java types of the method’s input
parameters (if the method has no input arguments, the `method-params`
element contains no `method-param` elements). Arrays are specified by
the array element’s type, followed by one or more pair of square
brackets (e.g. `int[][]`).

If both styles 3 and 4 are used to define
method-level interceptors for the same bean, the relative ordering of
those method-level interceptors is undefined.

===== Examples

Examples of the usage of the
`interceptor-binding` syntax are given below.

*Style 1:* The following interceptors are
default interceptors. They will be invoked in the order specified.
[source, xml]
----
<interceptor-binding>
    <target-name>*</target-name>
    <interceptor-class>org.acme.MyDefaultIC</interceptor-class>
    <interceptor-class>org.acme.MyDefaultIC2</interceptor-class>
</interceptor-binding>
----

*Style 2:* The following interceptors are
the class-level interceptors of the `EmployeeService` class. They will
be invoked in the order specified after any default interceptors.
[source, xml]
----
<interceptor-binding>
    <target-name>EmployeeService</target-name>
    <interceptor-class>org.acme.MyIC</interceptor-class>
    <interceptor-class>org.acme.MyIC2</interceptor-class>
</interceptor-binding>
----

*Style 3:* The following interceptors apply
to all the `myMethod` methods of the `EmployeeService` class. They will
be invoked in the order specified after any default interceptors and
class-level interceptors.
[source, xml]
----
<interceptor-binding>
    <target-name>EmployeeService</target-name>
    <interceptor-class>org.acme.MyIC</interceptor-class>
    <interceptor-class>org.acme.MyIC2</interceptor-class>
    <method-name>myMethod</method-name>
</interceptor-binding>
----

The following example illustrates more
complex parameter types. The method `myMethod(char s, int i,
int[] iar, mypackage.MyClass mycl, mypackage.MyClass[][]
myclaar)` would be specified as:
[source, xml]
----
<interceptor-binding>
    <target-name>EmployeeService</target-name>
    <interceptor-class>org.acme.MyIC</interceptor-class>
    <method-name>myMethod</method-name>
    <method-params>
        <method-param>char</method-param>
        <method-param>int</method-param>
        <method-param>int[]</method-param>
        <method-param>mypackage.MyClass</method-param>
        <method-param>mypackage.MyClass[][]</method-param>
    </method-params>
</interceptor-binding>
----

The following example illustrates
constructor-level interceptors that apply to all constructors of the
`EmployeeService` class. They will be invoked in the order specified
after any default interceptors and class-level interceptors.
[source, xml]
----
<interceptor-binding>
    <target-name>EmployeeService</target-name>
    <interceptor-class>org.acme.MyIC</interceptor-class>
    <interceptor-class>org.acme.MyIC2</interceptor-class>
    <method-name>EmployeeService</method-name>
</interceptor-binding>
----

*Style 4:* The following interceptor
element refers to the `myMethod(String firstName, String LastName)`
method of the `EmployeeService` class.
[source, xml]
----
<interceptor-binding>
    <target-name>EmployeeService</target-name>
    <interceptor-class>org.acme.MyIC</interceptor-class>
    <method-name>myMethod</method-name>
    <method-params>
        <method-param>java.lang.String</method-param>
        <method-param>java.lang.String</method-param>
    </method-params>
</interceptor-binding>
----

The following example illustrates
constructor-level interceptors that apply to the specific constructor of
the `EmployeeService` class.
[source, xml]
----
<interceptor-binding>
    <target-name>EmployeeService</target-name>
    <interceptor-class>org.acme.MyIC</interceptor-class>
    <interceptor-class>org.acme.MyIC2</interceptor-class>
    <method-name>EmployeeService</method-name>
    <method-params>
        <method-param>org.acme.Account</method-param>
        <method-param>java.lang.String</method-param>
    </method-params>
</interceptor-binding>
----

The following example illustrates the total
ordering of interceptors using the `interceptor-order` element:
[source, xml]
----
<interceptor-binding>
    <target-name>EmployeeService</target-name>
    <interceptor-order>
        <interceptor-class>org.acme.MyIC
        </interceptor-class>
        <interceptor-class>org.acme.MyDefaultIC
        </interceptor-class>
        <interceptor-class>org.acme.MyDefaultIC2
        </interceptor-class>
        <interceptor-class>org.acme.MyIC2
        </interceptor-class>
    </interceptor-order>
</interceptor-binding>
----
