[[a1]]
== Introduction

This is the specification of the Jakarta(R) Enterprise
Beans architecture. The Enterprise Beans architecture is an
architecture for the development and deployment of component-based
business applications. Applications written using the Enterprise
Beans architecture are scalable, transactional, and multi-user
secure. These applications may be written once, and then deployed on any
server platform that supports the Enterprise Beans specification.

=== Target Audience

_The target audiences for this specification
are the vendors of transaction processing platforms, vendors of
enterprise application tools, and other vendors who want to support the
Enterprise Beans technology in their products._

_Many concepts described in this document are
system-level issues that are transparent to the Enterprise Beans
application programmer._

[[a6]]
=== What is New in This Release

The Enterprise Beans 4.0 specification is a breaking change from
prior Enterprise Beans specifications delivering a namespace change
from `javax` to `jakarta` across the API along with removal of
deprecated APIs.

* _All `javax.ejb` namespace/packages have been renamed to `jakarta.ejb`._

* _Removed the methods relying on `java.security.Identity` which has
been removed from the Java 14._

* _Removed the methods relying on Jakarta XML RPC to reflect the removal of
XML RPC from the Jakarta EE 9 Platform._

* _Removed the deprecated `EJBContext.getEnvironment()` method._

* _Removed the "`Support for Distributed Interoperability`" to reflect
the removal of CORBA from Java 11 and the Jakarta EE 9 Platform._

* _Marked the Enterprise Beans 2.x API Group as "`Optional`"._

* _``@Schedule`` annotation is now repeatable._

=== What was New in Jakarta Enterprise Beans 3.2

The Jakarta Enterprise Beans 3.2 <<a9895>> architecture is the first official
release from the Eclipse Foundation under the specification's new name of
"`Jakarta Enterprise Beans`" after the successful donation of Enterprise JavaBeans
by Oracle.

The Jakarta Enterprise Beans 3.2 release is identical to Enterprise JavaBeans 3.2
and only differs by name and license.

=== What was New in Enterprise JavaBeans 3.2

The Enterprise JavaBeans 3.2 <<a9891>> architecture
extends Enterprise JavaBeans to include the following new functionality
and simplifications to the earlier Enterprise JavaBeans APIs:

* _Made support for the following features
optional in this release and moved their description to a separate 
Enterprise JavaBeans Optional Features <<a9890>> document:_

** _Enterprise JavaBeans 2.1 and earlier Entity Bean Component
Contract for Container-Managed Persistence_
** _Enterprise JavaBeans 2.1 and earlier Entity Bean Component
Contract for Bean-Managed Persistence_
** _Client View of an Enterprise JavaBeans 2.1 and earlier
Entity Bean_
** _Enterprise JavaBeans QL: Query Language for
Container-Managed Persistence Query Methods_
** _Jakarta XML RPC Based Web Service Endpoints_
** _Jakarta XML RPC Web Service Client View_

* _Enhanced message-driven beans contract with a
no-methods message listener interface to expose all public methods as
message listener methods._

* _Defined the Enterprise JavaBeans API Groups with clear rules
for an Enterprise JavaBeans Lite Container to support other API groups._

* _Added container provided security role named
"```**```" to indicate any authenticated caller independent of the actual role
name._

* _Extended the Enterprise JavaBeans Lite Group to include local
asynchronous session bean invocations and non-persistent Enterprise JavaBeans Timer
Service._

* _Added an option for the lifecycle callback
interceptor methods of stateful session beans to be executed in a
transaction context determined by the lifecycle callback method's
transaction attribute._

* _Introduced an option to disable passivation
of stateful session beans._

* _Enhanced the TimerService API to access all
active timers in the Enterprise JavaBeans module._

* _Enhanced the embeddable EJBContainer to
implement `AutoCloseable` interface._

* _Removed restrictions on `jakarta.ejb.Timer` and
`jakarta.ejb.TimerHandle` that required references to be used only inside a
bean._

* _Relaxed default rules for a session bean to
designate its implemented interfaces as local or as remote business
interfaces._

* _Enhanced the list of standard Jakarta(R) Messaging MDB
activation properties._

* _Simplified requirements for definition of a
security role using the ejb deployment descriptor._

* _Removed restriction on obtaining the current
class loader; replaced '`must not`' with '`should exercise caution`' when
using the Java I/O package._

=== What was New in Enterprise JavaBeans 3.1

The Enterprise JavaBeans 3.1 <<a9893>> architecture extended
Enterprise JavaBeans to include the following new functionality and
simplifications to the earlier Enterprise JavaBeans APIs:

* _A simplified local view that provides
session bean access without a separate local business interface._

* _Packaging and deployment of Enterprise JavaBeans components
directly in a `.war` file without an ejb-jar file._

* _An embeddable API for executing Enterprise JavaBeans
components within a Java SE environment._

 * _A singleton session bean component that
provides easy access to shared state as well as application startup and
shutdown callbacks._

* _Automatically created Enterprise JavaBeans Timers._

* _Calendar-based Enterprise JavaBeans Timer expressions._

* _Asynchronous session bean invocations._

* _The definition of a lightweight subset of
Enterprise JavaBeans functionality that is provided within the Jakarta(R) EE
Web Profile._

* _A portable global JNDI name syntax for
looking up Enterprise JavaBeans components._

==== What was New in Enterprise JavaBeans 3.0

The Enterprise JavaBeans 3.0 <<a9894>> architecture
extended Enterprise JavaBeans to include the following new functionality
and simplifications to the earlier Enterprise JavaBeans APIs:

* _Definition of the Java language metadata
annotations that can be used to annotate Enterprise JavaBeans applications. These
metadata annotations are targeted at simplifying the developer’s task,
at reducing the number of program classes and interfaces the developer
is required to implement, and at eliminating the need for the developer
to provide an Enterprise JavaBeans deployment descriptor._

* _Specification of programmatic defaults,
including for metadata, to reduce the need for the developer to specify
common, expected behaviors and requirements on the Enterprise JavaBeans container. A
"configuration by exception" approach is taken whenever possible._

* _Encapsulation of environmental dependencies
and JNDI access through the use of annotations, dependency injection
mechanisms, and simple lookup mechanisms._

* _Simplification of the enterprise bean
types._

* _Elimination of the requirement for Enterprise JavaBeans
component interfaces for session beans. The required business interface
for a session bean can be a plain Java interface rather than an
`EJBObject`, `EJBLocalObject`, or `java.rmi.Remote` interface._

* _Elimination of the requirement for home
interfaces for session beans._

* _Simplification of entity persistence
through the Jakarta(R) Persistence <<a9851>>. 
Support for light-weight domain modeling, including inheritance and
polymorphism._

* _Specification of Java language metadata
annotations and XML deployment descriptor elements for the
object/relational mapping of persistent entities <<a9851>>._

* _A query language for Jakarta Persistence that
is an extension to Enterprise JavaBeans QL, with addition of projection, explicit inner
and outer join operations, bulk update and delete, subqueries, and
group-by. Addition of a dynamic query capability and support for native
SQL queries._

* _An interceptor facility for session beans
and message-driven beans._

* _Reduction of the requirements for usage of
checked exceptions._

* _Elimination of the requirement for the
implementation of callback interfaces._

=== Acknowledgements

The Enterprise Beans 4.0 specification work was done under the Jakarta
EE Specification Process (JESP).

=== Acknowledgements for Enterprise JavaBeans 3.2

The Enterprise JavaBeans 3.2 specification work was
conducted as part of JSR-345 under the Java Community Process Program.
This specification is the result of the collaborative work of the
members of the Enterprise JavaBeans 3.2 Expert Group: Caucho Technology, Inc: Reza
Rahman; IBM: Jeremy Bauer; Oracle: Marina Vatkina, Linda DeMichiel; OW2:
Florent Benoit; Pramati Technologies: Ravikiran Noothi; RedHat: Pete
Muir, Carlo de Wolf; TmaxSoft, Inc.: Miju Byon; individual members: Adam
Bien; David Blevins; Antonio Goncalves; Stefan Heldt; Richard Hightower,
Jean-Louis Monteiro.

[[a56]]
=== Organization of the Specification Documents

This specification is organized into the
following documents:

* Enterprise Beans Core Features

* Enterprise Beans Optional Features

This Enterprise Beans Core Features document defines the
contracts and requirements for the use and implementation of Enterprise Beans. 
These contracts include those for the Enterprise Beans 4.0 API, as well as
for the earlier Enterprise Beans API that is required to be supported in this
release. See <<a9423>> for coverage of the Enterprise Beans API requirements.

The Enterprise Beans Optional Features document <<a9890>> defines the contracts and
requirements for the use and implementation of features support for
which has been made optional as of Enterprise JavaBeans, 3.2. These
contracts are separated from the core contracts requirements of the Enterprise JavaBeans
3.1 specification.

=== Document Conventions

The regular font is used for
information that is prescriptive by the Enterprise Beans specification.

_The italic font is used for paragraphs
that contain descriptive information, such as notes describing typical
use, or notes clarifying the text with prescriptive specification._

`The monospace font is used for code examples.`

