[[a2000]]
== Persistence

The model for persistence and
object/relational mapping was considerably revised and enhanced in the
Enterprise Beans 3.0 release. The contracts and requirements for
persistent entities are defined by the "_Jakarta Persistence_"
specification <<a9851>>, which also contains
the full specification of the Jakarta Persistence query language and the
metadata for object/relational mapping.


:opt-doc: ./enterprise-beans-spec-opt-{revnumber}.adoc

The client view of entity beans under the
earlier Enterprise Beans 2.1 programming model, the contracts for Enterprise Beans 2.1 Entity
Beans with Container-Managed Persistence, the contracts for the Enterprise Beans QL
query language, the contracts for Enterprise Beans 2.1 Entity Beans with Bean-Managed
Persistence, and the contracts for Enterprise Beans 1.1 Entity Beans with
Container-Managed Persistence are described in the Enterprise Beans Optional Features
document <<a9890>>. See
<<{opt-doc}#a41, Chapter 3>>,
<<{opt-doc}#a384, Chapter 4>>,
<<{opt-doc}#a1840, Chapter 5>>,
<<{opt-doc}#a2456, Chapter 6>> and 
<<{opt-doc}#a3071, Chapter 7>> respectively.
