[[a9849]]
[bibliography]
== Related Documents

- [[[a9850, 1]]] Jakarta Enterprise Beans, Core Features 3.2. (this specification) 
https://jakarta.ee/specifications/enterprise-beans/3.2/.

- [[[a9851, 2]]] Jakarta Persistence 2.2. 
https://jakarta.ee/specifications/persistence/2.2/.

- [[[a9852, 3]]] Enterprise JavaBeans™,
version 2. (EJB 2.1).
http://www.oracle.com/technetwork/java/javaee/ejb/index.html.

- [[[a9853, 4]]] JavaBeans™.
http://www.oracle.com/technetwork/java/javase/tech/index-jsp-138795.html.

- [[[a9854, 5]]] Java™ Naming and Directory
Interface 1.2 Specification (JNDI).
http://docs.oracle.com/javase/7/docs/technotes/guides/jndi/index.html.

- [[[a9855, 6]]] Java Remote Method
Invocation (RMI).
http://docs.oracle.com/javase/7/docs/technotes/guides/rmi/.

- [[[a9856, 7]]] Java™ Security.
http://www.oracle.com/technetwork/java/javase/tech/index-jsp-136007.html.

- [[[a9857, 8]]] Jakarta Transactions 1.3. 
https://jakarta.ee/specifications/transactions/1.3/.

- [[[a9858, 9]]] Java™ Transaction Service,
version 1.0 (JTS).
http://www.oracle.com/technetwork/java/javaee/jts-spec095-1508547.pdf.

- [[[a9859, 10]]] IDL To Java™ Language
Mapping Specification. http://www.omg.org/cgi-bin/doc?ptc/2000-01-08.

- [[[a9860, 11]]] Transaction Service
Specification (OTS). http://www.omg.org/cgi-bin/doc?ptc/2001-11-03.

- [[[a9861, 12]]] Jakarta EE Platform 8. 
https://jakarta.ee/specifications/platform/8/.

- [[[a9862, 13]]] Jakarta Messaging 2.0. 
https://jakarta.ee/specifications/messaging/2.0/.

- [[[a9863, 14]]] Jakarta Connectors 1.7. 
https://jakarta.ee/specifications/connectors/1.7/.

- [[[a9864, 15]]] Enterprise JavaBeans™ to
CORBA Mapping
v1.1.http://www.oracle.com/technetwork/java/javaee/ejb/index.html.

- [[[a9865, 16]]] CORBA
2.3.1 Specification. http://www.omg.org/cgi-bin/doc?formal/99-10-07.

- [[[a9866, 17]]] CORBA Naming Service.
http://www.omg.org/spec/NAM/.

- [[[a9867, 18]]]Interoperable Name Service
FTF document. http://www.omg.org/cgi-bin/doc?ptc/00-08-07.

- [[[a9868, 19]]] RFC 2246: The TLS
Protocol. ftp://ftp.isi.edu/in-notes/rfc2246.txt.

- [[[a9869, 20]]] RFC 2712: Addition of
Kerberos Cipher Suites to Transport Layer Security.
ftp://ftp.isi.edu/in-notes/rfc2712.txt.

- [[[a9870, 21]]] The SSL Protocol Version
3.0. http://tools.ietf.org/html/rfc6101.

- [[[a9871, 22]]] Common Secure
Interoperability Version 2 Final Available Specification.
http://www.omg.org/cgi-bin/doc?ptc/2001-06-17.

- [[[a9872, 23]]] Database Language SQL.
ANSI X3.135-1992 or ISO/IEC 9075:1992.

- [[[a9873, 24]]] Jakarta XML RPC 1.1. 
https://jakarta.ee/specifications/xml-rpc/1.1/.

- [[[a9874, 25]]]Web Services Description
Language (WSDL) 1.1. _http://www.w3.org/TR/wsdl._

- [[[a9875, 26]]] W3C: SOAP 1.2.
_http://www.w3.org/TR/SOAP/._

- [[[a9876, 27]]] The Java Virtual Machine
Specification.

- [[[a9877, 28]]] JDBC™ 4.1 API (JDBC
specification). http://jcp.org/en/jsr/detail?id=221.

- [[[a9878, 29]]] Jakarta Web Services Metadata 2.1. 
https://jakarta.ee/specifications/web-services-metadata/2.1/.

- [[[a9879, 30]]] Jakarta Enterprise Web Services 1.4.
https://jakarta.ee/specifications/enterprise-ws/1.4/

- [[[a9881, 31]]] Jakarta XML Web Services 2.3. 
https://jakarta.ee/specifications/xml-web-services/2.3/

- [[[a9882, 32]]] JAR File Specification,
http://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html.

- [[[a9883, 33]]] Java™ Platform, Standard
Edition, v7 API Specification (Java SE).
http://docs.oracle.com/javase/7/docs/api/index.html.

- [[[a9884, 34]]] Enterprise JavaBeans™, version 3.0. (EJB
3.0). http://www.oracle.com/technetwork/java/javaee/ejb/index.html.

- [[[a9885, 35]]] List of zoneinfo time
zones: http://en.wikipedia.org/wiki/List_of_tz_zones.

- [[[a9886, 36]]] Jakarta Managed Beans 1.0. 
https://jakarta.ee/specifications/managedbeans/1.0/.

- [[[a9887, 37]]] Jakarta Interceptors 1.2. 
https://jakarta.ee/specifications/interceptors/1.2/.

- [[[a9888, 38]]] Jakarta Context Dependency Injection 2.0 
https://jakarta.ee/specifications/cdi/2.0/.

- [[[a9889, 39]]] Jakarta RESTful Web Services 2.1
https://jakarta.ee/specifications/restful-ws/2.1/.

- [[[a9890, 40]]] Jakarta Enterprise Beans, Optional Features 3.2
https://jakarta.ee/specifications/enterprise-beans/3.2/.

- [[[a9891, 41]]] Enterprise JavaBeans™,
version 3.1. (EJB 3.1). _http://jcp.org/en/jsr/detail?id=318._
