[appendix]
[[a9892]]
== Revision History

This appendix lists the significant changes
that have been made to this document during the development of the EJB
3.2 Specification.

=== Early Draft 1



{empty}link:Ejb.html#a1[See
Introduction]

Update in preparation for EJB 3.2.

Minor editorial changes.

{empty}link:Ejb.html#a66[See
Overview]

Removed Persistence Provider role, as Java
Persistence is now a separate specification

Rewrote Pruning section to reflect the EJB
features which are being made optional in the EJB 3.2 release. Added
references to the new EJB Optional Features document
link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.].

Minor editorial changes.

{empty}link:Ejb.html#a204[See Client
View of a Session Bean]

Reorganized section
link:Ejb.html#a207[See Overview].

Clarified terminology used in the document
when reference to client view interfaces in section
link:Ejb.html#a224[See Local, Remote, and Web Service Client
Views].

Reorganization of sections
link:Ejb.html#a235[See Remote Clients],
link:Ejb.html#a242[See Local Clients],
link:Ejb.html#a271[See Web Service Clients].

Relocated Object Identity discussion into
section link:Ejb.html#a564[See Object Identity].

Moved section 3.5.2 to the EJB Optional
Features document link:Ejb.html#a9890[See EJB 3.2 Optional
Features http://jcp.org/en/jsr/detail?id=345.] and removed references to
JAX-RPC API and entity beans.

Minor editorial changes.

{empty}link:Ejb.html#a608[See
Session Bean Component Contract]

Added caveat about javax.mail.Session object
and stateful session bean passivation to section
link:Ejb.html#a639[See Instance Passivation and Conversational
State].

Flagged open issues in sections
link:Ejb.html#a682[See The SessionContext Interface],
link:Ejb.html#a722[See The SessionBean Interface],
link:Ejb.html#a736[See The Session Synchronization
Notifications for Stateful Session Beans],
link:Ejb.html#a767[See Stateful Session Bean Removal],
link:Ejb.html#a816[See java:module],
link:Ejb.html#a947[See Operations Allowed in the Methods of a
Stateful Session Bean Class] (two issues),
link:Ejb.html#a1065[See Stateless Session Beans],
link:Ejb.html#a1085[See Operations Allowed in the Methods of a
Stateless Session Bean Class],

{empty}Removed references to JAX-RPC API and
entity beans. Moved most of the section 4.9.13 to the EJB Optional
Features document link:Ejb.html#a9890[See EJB 3.2 Optional
Features http://jcp.org/en/jsr/detail?id=345.]

Minor editorial changes and reorganization

{empty}link:Ejb.html#a1702[See
Message-Driven Bean Component Contract]

Minor editorial changes.

Flagged open issue in section
link:Ejb.html#a1751[See The MessageDrivenContext Interface].

{empty}link:Ejb.html#a2000[See
Persistence]

Noticed optionality of support for EJB 2.1
and 1.1 entity beans and EJB QL 1.1 and added references to the
corresponding chapters of the EJB Optional Features document
link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.].

{empty}link:Ejb.html#a2004[See
Interceptors]

Minor editorial changes only.

{empty}link:Ejb.html#a2172[See
Support for Transactions]

{empty}Moved text related to the entity beans
to the EJB Optional Features document link:Ejb.html#a9890[See
EJB 3.2 Optional Features http://jcp.org/en/jsr/detail?id=345.]

{empty}Flagged issues in sections
link:Ejb.html#a2250[See Enterprise Beans Using Bean-Managed
Transaction Demarcation], link:Ejb.html#a2538[See Specification
of the Transaction Attributes for a Bean’s Methods],
link:Ejb.html#a2624[See Use of the container-transaction
element]

Miscellaneous minor editorial changes.

{empty}link:Ejb.html#a2940[See
Exception Handling]

Moved sections 14.2.2.1and 14.3.8 to the EJB
Optional Features document link:Ejb.html#a9890[See EJB 3.2
Optional Features http://jcp.org/en/jsr/detail?id=345.], removed
references to the JAX-RPC web service endpoint interface and to the
entity beans.

Minor editorial changes.

{empty}link:Ejb.html#a3308[See
Support for Distributed Interoperability]

Removed references to the JAX-RPC web service
endpoint interface and to the entity beans.

Editorial changes.

{empty}link:Ejb.html#a3613[See
Enterprise Bean Environment]

Mostly editorial changes

Corrected missing references to no-interface
view

{empty}Minor expansion to description in
section link:Ejb.html#a3915[See Bean Provider’s
Responsibilities]

Removed references to the entity beans and
replaced entity bean type with a session bean in examples in sections
link:Ejb.html#a3998[See Declaration of EJB References in
Deployment Descriptor] and link:Ejb.html#a4057[See Application
Assembler’s Responsibilities].

Cleaned up section
link:Ejb.html#a4057[See Application Assembler’s
Responsibilities] in attempt to clarify the use and syntax of the
ejb-link element. These changes require further review.

Tried to cleanup section
link:Ejb.html#a4133[See Deployer’s Responsibility]. This is
flagged for further review.

{empty}link:Ejb.html#a4945[See
Security Management]

Mostly editorial changes

Removed references to the entity beans

{empty}Corrected missing reference to
no-interface view in section link:Ejb.html#a5121[See
Responsibilities of the Bean Provider and/or Application Assembler] and
to business interfaces in section link:Ejb.html#a5442[See Audit
Trail]

{empty}link:Ejb.html#a5456[See Timer
Service]

{empty}Added clarifications to section
link:Ejb.html#a5465[See Bean Provider’s View of the Timer
Service]

{empty}Removed references to the EJB 2.x
entity beans and moved section 18.4.5 to the EJB Optional Features
document link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]

Flagged a number of open issues and tried to
clarify. These require review/discussion.

{empty}link:Ejb.html#a5804[See
Deployment Descriptor]

Added a note that entity beans elements are
described in the EJB Optional Features document
link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]. Moved description of the
persistence related elements to the new document. Removed references to
the entity beans where possible.

Open issues for difficult to parse paragraphs
in sections link:Ejb.html#a5815[See Bean Provider’s
Responsibilities] (for no-interface view) and
link:Ejb.html#a5865[See Application Assembler’s Responsibility]
(first paragraph).

Miscellaneous editorial changes.

{empty}link:Ejb.html#a9294[See
Packaging]

Rewrote to better clarify intended semantics

{empty}Removed references to the entity beans
and moved sections 20.4.5 and 20.4.6 to the EJB Optional Features
document link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]

Flagged a number of open issues. See section
link:Ejb.html#a9314[See Enterprise Beans Packaged in a .war
file], link:Ejb.html#a9324[See Visibility of the Local Client
View], link:Ejb.html#a9390[See The Client View and the
ejb-client JAR File], link:Ejb.html#a9397[See Requirements for
Clients].

{empty}link:Ejb.html#a9423[See
Runtime Environment]

Section link:Ejb.html#a9622[See EJB
Interfaces and Annotations Requirements]. Reinstated requirements around
JPA contracts.

Miscellaneous editorial changes.

{empty}link:Ejb.html#a9735[See
Embeddable Usage]

Miscellaneous editorial changes.

Flagged a couple of open issues related to
requirements on the container in section link:Ejb.html#a9803[See
Embeddable Container Bootstrapping].

{empty}link:Ejb.html#a9826[See
Responsibilities of EJB Roles]

Removed reference to Persistence Provider
role.

Original Chapter 7, “Client View of an EJB
2.1 Entity Bean”

{empty}Moved to the EJB Optional Features
document link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]

Original Chapter 8, “EJB 2.1 Entity Bean
Component Contract for Container-Managed Persistence”

{empty}Moved to the EJB Optional Features
document link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]

Original Chapter 9, “EJB QL: EJB 2.1 Query
Language for Container-Managed Persistence Query Methods”

{empty}Moved to the EJB Optional Features
document link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]

Original Chapter 10, “EJB 2.1 Entity Bean
Component Contract for Bean-Managed Persistence”

{empty}Moved to the EJB Optional Features
document link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]

Original Chapter 11, “EJB 1.1 Entity Bean
Component Contract for Container-Managed Persistence”

{empty}Moved to the EJB Optional Features
document link:Ejb.html#a9890[See EJB 3.2 Optional Features
http://jcp.org/en/jsr/detail?id=345.]

=== Early Draft 2



{empty}link:Ejb.html#a1[See
Introduction]

Added expert group memebers of JSR-345

{empty}Updated section
link:Ejb.html#a6[See What is New in This Release]

Fixed typo

{empty}link:Ejb.html#a66[See
Overview]

Clarified Application Assembler role

{empty}link:Ejb.html#a608[See
Session Bean Component Contract]

Minor editorial changes

Clarified _getContextData_ method

Resolved that PostConstruct callback method
can be exposed as a business method

Clarified when _wasCancelCalled method can be
called_

{empty}Clarify usage of _getBusinessObject_
method in sections link:Ejb.html#a682[See The SessionContext
Interface]

Replaced “common bean state” with “bean
instance variables”

Clarified that if a singleton session bean
fails to initialize, attempted invocations on the singleton session bean
result in an the javax.ejb.NoSuchEJBException exception

Clarified that at most one afterBegin,
beforeCompletion, afterCompletion method can be used for a bean

Clarified that if there are multiple remove
methods, their retainIfException values can differ

Removed clarification request from section
link:Ejb.html#a722[See The SessionBean Interface], last
paragraph as the text seems clear to the EG

New: Added support for the lifecycle callback
interceptor methods of stateful session beans to execute in a
transaction context determined by the bean’s transaction management type
and any applicable transaction attribute

{empty}New: Added _getRollbackOnly and
setRollbackOnly_ to permitted operations in lifecycle callback
interceptor methods with container-managed transaction demarcation in
link:Ejb.html#a953[See Operations Allowed in the Methods of a
Stateful Session Bean]

Renamed section
link:Ejb.html#a921[See Stateful Session Beans] to be consistent
with those for stateless and singleton session beans

{empty}link:Ejb.html#a1702[See
Message-Driven Bean Component Contract]

Clarified _getContextData_ method

Minor editorial changes

{empty}link:Ejb.html#a2004[See
Interceptors]

Clarified _getContextData_ method

Minor editorial changes

New: Added support for the lifecycle callback
interceptor methods of stateful session beans to execute in a
transaction context determined by the bean’s transaction management type
and any applicable transaction attribute

{empty}link:Ejb.html#a2172[See
Support for Transactions]

Minor editorial changes

Clarified that the bean-managed transaction
must be completed before the last AroundInvoke interceptor method
completes

Confirmed that no further clarification is
necessary for the singleton session bean PostConstruct and PreDestroy
bullet item

Added singleton PostConstruct and PreDestroy
methods to the list of methods which can use container-transaction
element to define the transaction attributes

New: Added support for the lifecycle callback
interceptor methods of stateful session beans to execute in a
transaction context determined by the bean’s transaction management type
and any applicable transaction attribute

{empty}link:Ejb.html#a2940[See
Exception Handling]

Clarified class hierarchy rules for an
application exception

Clarified how application exception is
defined

New: Added support for the lifecycle callback
interceptor methods of stateful session beans to execute in a
transaction context determined by the bean’s transaction management type
and any applicable transaction attribute

{empty}link:Ejb.html#a3613[See
Enterprise Bean Environment]

Minor editorial changes

No further clarifications needed in the
module name description

No further clarifications needed in section
link:Ejb.html#a4133[See Deployer’s Responsibility] Deployer role

Fixed the list of valid Java types for
environment entry values to match Java EE
Specification

{empty}link:Ejb.html#a5456[See Timer
Service]

Minor editorial changes

Clarified EJB timers creation and expiration
in regards to the number of JVM instances

Clarified the case when the dayOfMonth
attribute has a non-wildcard value and the dayOfWeek attribute has a
non-wildcard value

Added a note that the “5th” is the highest
ordinal number allowed as the value for the dayOfMonth

Clarified that the getTimers method returns
all active timers associated with the bean

Clarified that the timeout callback method
for the programmatically-created timers can also be associated with the
same method as automatically-created timers

Clarified use of method-param of the
timeout-method element for matching the timeout methods in the bean
class

Removed reference to automatically created
timers from the rule about invoking a no-arg timeout callback method

Clarified bean class rules for
programmatically created timers

{empty}link:Ejb.html#a5804[See
Deployment Descriptor]

Clarified the text on how the Application
Assembler assembles enterprise beans into deployment units.

Confirmed that the new text about Enterprise
bean’s no-interface view is correct

Minor editorial changes

{empty}link:Ejb.html#a9294[See
Packaging]

Added a note that a .war file may contain
enterprise bean classes in a combination of classes within the
WEB-INF/classes directory and one or more jar files within the
WEB-INF/lib directory

Confirmed that text describing visibility of
the local client view and client view is correct

Confirmed that the requirements for the jar
file that contains the client are correct

Minor editorial changes

{empty}link:Ejb.html#a9423[See
Runtime Environment]

Minor editorial changes

Clarified the lists under JNDI requirements
on how they apply to the Full Java EE Platform and the Web Profile and
the embeddable EJB container

{empty}New: Added 2.x Local Home/Component to
link:Ejb.html#a9442[See EJB API Groups]

{empty}New: Added asynchronous session bean
invocations and non-persistent EJB Timer Service support to EJB Lite and
link:Ejb.html#a9442[See EJB API Groups]

New: Removed restriction to obtain the
current class loader; changed ‘must not’ to ‘should exercise caution’
when using the Java I/O package

New: Changed the statement in section
link:Ejb.html#a9726[See Stateful Session Beans] about
transaction context of invocation of the PostConstruct lifecycle
callbacks and _Init_ method to be determined by the bean’s transaction
management type and any applicable transaction attribute.

{empty}link:Ejb.html#a9735[See
Embeddable Usage]

Clarified that A Container Provider
implementation must act as a service provider

Appendix B, “Open Issues and To-Do Items”
(removed)

{empty}http://java.net/jira/browse/EJB_SPEC[Moved
all non-resolved open issues to JIRA
(http://java.net/jira/browse/EJB_SPEC)]

[[a10047]]
=== Public Review Draft 1 & 2



{empty}link:Ejb.html#a1[See
Introduction]

Updated the rule: the lifecycle callback
interceptor methods of stateful session beans can be executed in a
transaction context determined by the lifecycle callback method's
transaction attribute

Updated "What is New in This Release"

{empty}link:Ejb.html#a66[See
Overview]

Minor editorial changes

{empty}link:Ejb.html#a204[See Client
View of a Session Bean]

Excluded methods defined on the
java.lang.Object class from the no-interface view

{empty}link:Ejb.html#a608[See
Session Bean Component Contract]

Excluded methods defined on the
java.lang.Object class from the no-interface view

{empty}Removed section on
javax.ejb.embeddable.appName as it is a duplicate of the section in
link:Ejb.html#a9735[See Embeddable Usage]

Specified javax.xml.ws.handler.MessageContext
instead of a non-deterministic MessageContex

Updated the rule: the lifecycle callback
interceptor methods of stateful session beans can be executed in a
transaction context determined by the lifecycle callback method's
transaction attribute

Updated the rule: only transaction attributes
REQUIRES_NEW or NOT_SUPPORTED (RequiresNew or NotSupported if the
deployment descriptor is used) are permitted for lifecycle callback
interceptor methods of stateful session beans

Restored the rule: invocation of the Init
method of stateful session beans occurs in an unspecified transaction
context

New: Added support for not passivation
capable stateful session beans

New: Specified the relaxed default rules for
designating implemented interfaces for a session bean as local or as
remote business interfaces

{empty}link:Ejb.html#a1702[See
Message-Driven Bean Component Contract]

Minor editorial changes

{empty}link:Ejb.html#a2172[See
Support for Transactions]

Editorial changes in examples

Specified transaction completion rules for
BMT beans when AroundInvoke interceptor methods are applied to a
business method, or AroundTimeout interceptor methods are applied to a
timeout callback method

Updated the rule: the lifecycle callback
interceptor methods of stateful session beans to be executed in a
transaction context determined by the lifecycle callback method's
transaction attribute

Updated the rule: only transaction attributes
REQUIRES_NEW or NOT_SUPPORTED (RequiresNew or NotSupported if the
deployment descriptor is used) are permitted for lifecycle callback
interceptor methods of stateful session beans

Clarified use of the container-transaction
element. Added singleton PostConstruct and PreDestroy methods and listed
limitations of using stateful session bean PostConstruct, PreDestroy,
PrePassivate or PostActivate methods as the methods which can use
container-transaction element to define the transaction attributes

{empty}link:Ejb.html#a3613[See
Enterprise Bean Environment]

Added details about elements of the EJB
annotation

{empty}link:Ejb.html#a5456[See Timer
Service]

Added _getAllTimers_ method

{empty}link:Ejb.html#a5804[See
Deployment Descriptor]

Minor editorial changes

{empty}link:Ejb.html#a9294[See
Packaging]

Minor editorial changes

{empty}link:Ejb.html#a9423[See
Runtime Environment]

Removed embeddable API from the required
contents of EJB Lite and Full EJB API

Removed reference to the embeddable EJB
container from the list of objects that EJB container must make
available within an implementation of the Full Java EE Platform

Updated the rule: invocation of the
PostConstruct and PreDestroy lifecycle callbacks methods of stateful
session beans occurs in a transaction context determined by the method’s
transaction attribute, if any.

Restored the rule: invocation of the Init
method of stateful session beans with container-managed transaction
occurs in an unspecified transaction context

{empty}link:Ejb.html#a9694[See
Compatibility and Migration]

Created a separate chapter out of subsection

{empty}link:Ejb.html#a9735[See
Embeddable Usage]

Clarified that the embeddable EJB container
is to be used only within a Java SE environment

Clarified that Container Provider refers to
embeddable Container Provider

Fixed typo in the EJBContainer package

{empty}link:Ejb.html#a9892[See
Revision History]

Rearranged history with the latest changes
being at the end

=== Public Review Draft 3



{empty}link:Ejb.html#a1[See
Introduction]

Updated the rule: only local asynchronous
session bean invocations are supported in EJB Lite

{empty}link:Ejb.html#a608[See
Session Bean Component Contract]

Specified that the SessionContext object in a
the singleton session bean is thread-safe

{empty}link:Ejb.html#a1702[See
Message-Driven Bean Component Contract]

Added descriptions of the new standard
activation properties for JMS message-driven beans

Rearranged subsections on JMS message-driven
beans under a single section

Added requirements for the container provider
to publish the name which uniquely identifies the deployed MDB in the
JNDI naming context under java:comp/uniqueMDBName

Noted that the _MessageDriven annotation is a
component-defining annotation_

{empty}link:Ejb.html#a3613[See
Enterprise Bean Environment]

Specified that the SessionContext object in a
the singleton session bean is thread-safe

{empty}link:Ejb.html#a5456[See Timer
Service]

Clarified EJB timers distribution and
failover rules apply only to persistent timers

Clarified that non-persistent timers returned
by getTimers and getAllTimers methods are from the same JVM as the
caller

{empty}link:Ejb.html#a5804[See
Deployment Descriptor]

Explicitly listed the component-defining
annotations

{empty}link:Ejb.html#a9423[See
Runtime Environment]

Updated the rule: only local asynchronous
session bean invocations are supported in EJB Lite

Clarified that “Local” view in EJB Lite means
“Local business interface” view

Synchronized permissions in the Table
link:Ejb.html#a9591[See Java 2 Platform Security Policy for a
Standard EJB Container] with the permissions listed for the EJB
Components in the Java EE Platform Specification
link:Ejb.html#a9861[See Java™ Platform, Enterprise Edition
Specification Version 7 (Java EE). http://jcp.org/en/jsr/detail?id=342.]
Table EE.6-2.

{empty}link:Ejb.html#a9694[See
Compatibility and Migration]

Fixed typos and section numbering (left over
after moving it to its own chapter)

Noted that only 3.0 and 3.1 deployment
descriptors are required to be supported in EJB Lite for prior versions
of the applications

{empty}link:Ejb.html#a9735[See
Embeddable Usage]

Noted that during the processing of the
close() method, the embeddable container cancels all pending
asynchronous invocations and non-persistent timers

{empty}link:Ejb.html#a9849[See
Related Documents]

Updated to the latest versions of the related
documents

{empty}link:Ejb.html#a10047[See Public
Review Draft 1 & 2]

Marked that the changes reflect combined
changes in version 1 and 2

=== Public Review Draft 4



{empty}link:Ejb.html#a1[See
Introduction]

Updated "What is New in This Release"

{empty}Removed Interceptors specification
from the section link:Ejb.html#a56[See Organization of the
Specification Documents]

Minor editorial changes

{empty}link:Ejb.html#a66[See
Overview]

Added section on relationship to the CDI
Specification

Minor editorial changes

{empty}link:Ejb.html#a204[See Client
View of a Session Bean]

Minor editorial changes

{empty}link:Ejb.html#a608[See
Session Bean Component Contract]

Added a note on failover support being
undefined for not passivation capable stateful session beans

Noted the a bean class may declare a
constructor using Inject annotation in addition to a no-arg constructor,
if it is a CDI-enabled bean

Noted that a container can invoke the
_PreDestroy_ method on the instance without a client call to remove the
session object when the context to which the CDI-enabled bean instance
belongs to is destroyed

{empty}Reworded section
link:Ejb.html#a1518[See Session Bean’s Business Interface]

Added a footnote to “Operation Allowed”
tables on lifecycle callback method treated like a business method if
called through a business interface or a no-interface view

Replace restriction on asynchronous business
methods exposed through the component and web service client views, with
the statement that support is not required.

Added a note that concurrency management type
CONTAINER may be specified for stateful session beans, but doing so has
no impact on the semantics of concurrency management for such beans.

Minor editorial changes

{empty}link:Ejb.html#a1702[See
Message-Driven Bean Component Contract]

Removed requirements for the container
provider to publish the name which uniquely identifies the deployed MDB
in the JNDI naming context under java:comp/uniqueMDBName

Minor editorial changes

{empty}link:Ejb.html#a2004[See
Interceptors]

{empty}Described common rules for exception
in section link:Ejb.html#a2031[See Exception Handling]

Minor editorial changes

{empty}link:Ejb.html#a2172[See
Support for Transactions]

Split section “8.6.2 Container-Managed
Transaction Demarcation for Session Beans” into
link:Ejb.html#a2748[See Container-Managed Transaction
Demarcation for Session Beans] and link:Ejb.html#a2755[See
Container-Managed Transaction Demarcation for Business Methods] to allow
easier references from the Optional document

Split section “8.6.3 Container-Managed
Transaction Demarcation for Message-Driven Beans” into
link:Ejb.html#a2854[See Container-Managed Transaction
Demarcation for Message-Driven Beans] and
link:Ejb.html#a2858[See Container-Managed Transaction
Demarcation for Message Listener Methods] to follow layout of the
corresponding sections for session beans

{empty}Added a footnote that component
contract and client view of entity beans are described in the EJB
Optional Features document link:Ejb.html#a9890[See EJB 3.2
Optional Features http://jcp.org/en/jsr/detail?id=345.]

{empty}link:Ejb.html#a2940[See
Exception Handling]

Minor editorial changes

{empty}link:Ejb.html#a3308[See
Support for Distributed Interoperability]

Restored references to entity beans where
separating the rules added an unnecessary complexity. Added footnotes
that component contract and client view of entity beans are described in
the EJB Optional Features document.

{empty}link:Ejb.html#a3613[See
Enterprise Bean Environment]

Restored references to entity beans as
separating the rules added an unnecessary complexity. Added footnotes
that component contract and client view of entity beans are described in
the EJB Optional Features document.

{empty}link:Ejb.html#a4945[See
Security Management]

Restored references to entity beans as
separating the rules added an unnecessary complexity. Added footnotes
that component contract and client view of entity beans are described in
the EJB Optional Features document.

{empty}link:Ejb.html#a5456[See Timer
Service]

Updated the rule: Removed restriction that
timers returned by getAllTimers method can be cancelled only by the
owning bean.

Removed restrictions on javax.ejb.Timer and
javax.ejb.TimerHandle references to be used only inside a bean.

{empty}link:Ejb.html#a5804[See
Deployment Descriptor]

Updated XML Schema definition to the latest
version

Added a note that concurrency-management-type
Container may be specified for stateful session beans, but doing so has
no impact on the semantics of concurrency management for such beans.

{empty}link:Ejb.html#a9423[See
Runtime Environment]

Minor editorial changes

{empty}link:Ejb.html#a9694[See
Compatibility and Migration]

Noted that entity bean components and JAX-RPC
based web services endpoints are excluded from required support for
existing applications

{empty}link:Ejb.html#a9735[See
Embeddable Usage]

Added that EJBContainer class implements the
java.lang.AutoCloseable interface

=== Public Draft



Reworded the rule in section
link:Ejb.html#a1518[See Session Bean’s Business Interface] on
when all business interfaces must be explicitly designated as such

Minor editorial changes after experts review

=== Proposed Final Draft



Minor editorial changes

Updated rules for the activationConfig
properties to reflect changes to the JMS specification. Removed section
“Durable Subscription Name in Clustered Deployment”

Moved chapter “Specification of Interceptors
in the Deployment Descriptor” from the Interceptors specification back
to this document

Added that _PostActivate_ , and
_PrePassivate_ lifecycle callback methods follow requirements for the
lifecycle callback interceptor methods defined in the Interceptors
specification

Noted the a message-driven bean class may
declare a constructor using Inject annotation in addition to a no-arg
constructor, if it is a CDI-enabled bean

Added AroundConstruct to the list of
supported lifecycle callback methods.

Added references to the Interceptors
specification for bean instance creation rules if AroundConstruct
callback is declared on the associated interceptor class

Added _around-construct_ interceptor type to
the list of deployment descriptor elements used to specify the
interceptor methods of an interceptor class

Replaced newInstance() with a bean
constructor to allow for Inject constructor use cases

Updated to the final versions of the related
documents

Removed explicit 3.2 version where it is not
needed

New: Defined EJB API Groups.

Renamed Subsection “EJB Lite” to
link:Ejb.html#a9428[See EJB Lite and Other EJB API Groups].

Replaced table “Required contents of EJB Lite
and Full EJB API” with “EJB API Groups”

Added section link:Ejb.html#a9516[See
Support for Other EJB API Groups in an EJB Lite Container].

{empty}Added section
link:Ejb.html#a9527[See Integration with Other Technologies]

Updated related Embeddable Container
requirements (link:Ejb.html#a9799[See Runtime Environment]) to
not require .war file support

Updated XML Schema definition to the latest
version

Added section on relationship to the JAX-RS
Specification

New: Added Container provided security role
named “**” to indicate any authenticated caller independent of the
actual role name

Adjusted section
link:Ejb.html#a3701[See Simple Environment Entries], and fixed
the list of the naming context that the container must implement to be
consistent with the Java EE Platform specification

Added lookup-name to a deployment descriptor
override rules for a _Resource_ annotation

Replaced description of the
resource-ref and the resource-env-ref
elements with the references to the Java EE Platform specification

Updated section
link:Ejb.html#a9652[See JMS API Requirements] to reflect the
latest requirements in the JMS specification

Updated sections
link:Ejb.html#a9644[See JTA API Requirements] and
link:Ejb.html#a9650[See JDBC™ API Requirements] to match the
latest versions of the corresponding specification

Replaced footnote in section
link:Ejb.html#a1053[See Disabling Passivation of Stateful
Session Beans] with a text note on failover of stateful session beans
and use of passivation

New: Added message-driven bean with a
no-methods listener interface

Updated "What is New in This Release"

=== Final Release Candidate



Editorial changes

Specified that the unqualified bean class
name can be used as the value in the method-name element to bind
constructor-level interceptors

Simplified requirements for definition of a
security role using the ejb deployment descriptor

Restricted use of JTA transactional
interceptors with EJBs

Aligned environment entries requirements with
the Java EE Platform specification

Noted that if a transaction had been marked
for rollback, the value of the application exception rollback element
has no effect

Updated "What is New in This Release"

Updated XML Schema definition to the latest
version

Clarified that no-interface view and
no-methods interface message listener methods are non-static public
methods

Removed restriction on final modifier for
methods which are not exposed through a no-interface view or are not
message listener methods with a no-methods interface

=== Final Release



Finalized the rule on the final modifier for
methods of a session bean with a no-interface view and message-driven
beans with a no-methods listener interface
