[[a5456]]
== Timer Service

This chapter defines the EJB
container-managed Timer Service. The EJB Timer Service is a
container-provided service that allows the Bean Provider to register
enterprise beans for timer callbacks to occur according to a
calendar-based schedule, at a specified time, after a specified elapsed
time, or at specified intervals.

=== Overview



Enterprise applications that model
workflow-type business processes are dependent on notifications that
certain temporal events have occurred in order to manage the semantic
state transitions that are intrinsic to the business processes that they
model.

The EJB Timer Service is a container-managed
service that allows callbacks to be scheduled for time-based events. The
container provides a reliable and transactional notification service for
timed events. Timer notifications may be scheduled to occur according to
a calendar-based schedule, at a specific time, after a specific elapsed
duration, or at specific recurring intervals.

The Timer Service is implemented by the EJB
container. An enterprise bean accesses this service by means of
dependency injection, through the _EJBContext_ interface, or through
lookup in the JNDI namespace.

The EJB Timer Service is a coarse-grained
timer notification service that is designed for use in the modeling of
application-level processes. It is not intended for the modeling of
real-time events.

While timer durations are expressed in
millisecond units, this is because the millisecond is the unit of time
granularity used by the APIs of the Java SE platform. It is expected
that most timed events will correspond to hours, days, or longer periods
of time.

The following sections describe the Timer
Service with respect to the various individual EJB roles.

[[a5465]]
=== Bean Provider’s View of the Timer Service



The EJB Timer Service is a container-provided
service that allows enterprise beans to be registered for timer callback
methods to occur according to a calendar-based schedule, at a specified
time, after a specified elapsed time, or after specified intervals. The
Timer Service provides methods for the programmatic creation and
cancellation of timers, as well as for locating the timers that are
associated with a bean or with all beans in an EJB module. Timers can
also be created automatically by the container at deployment time based
on metadata in the bean class or in the deployment descriptor.

A timer is created to schedule timed
callbacks. The bean class of an enterprise bean that uses the Timer
Service can provide one or more timeout callback methods. A bean can
have one or more callback methods corresponding to automatically-created
timers as well as a callback method corresponding to one or more
programmatically-created timers.

For programmatically created timers, the
timeout callback method must either be a single method that is annotated
with the _Timeout_ annotation or the bean must implement the
_javax.ejb.TimedObject_ interface. The _javax.ejb.TimedObject_ interface
has a single method, the timer callback method _ejbTimeout_ .

For automatically created timers, the
Schedule annotation denotes its the timeout method.

Timers can be created for stateless session
beans, singleton session beans, message-driven
beanslink:#a10332[112]. Timers cannot be created for stateful
session beanslink:#a10333[113].

The timeout callback method invocation for a
timer that is created for a stateless session bean or a message-driven
bean may be called on any bean instance in the pooled state.

The timeout callback method for a
programmatically created persistent timer will be invoked on the JVM on
which the timer was created or on another JVM instance across which the
container is distributed. The timeout callback method for a
programmatically created non-persistent timer will be invoked on the JVM
on which the timer was created. The timeout callback method for a
programmatically created timer is invoked on a single JVM instance
regardless of the number of JVMs across which the container is
distributed.

For each automatically-created persistent
timer, the container creates a single persistent timer, regardless of
the number of JVMs across which the container is distributed. For
automatically-created non-persistent timers, the container creates a new
non-persistent timer during application initialization for each JVM
across which the container is distributed.

In the event of a container crash or
container shutdown, the timeout callback method for a persistent timer
that has not been cancelled will be invoked on a new JVM when the
container is restarted or on another JVM instance across which the
container is distributed. This rule applies to both programmatically or
automatically created persistent timers.

When the time specified at timer creation
elapses, the container invokes the associated timeout callback method of
the bean. A timer may be cancelled before its expiration. If a timer is
cancelled, its associated timeout callback method is not
calledlink:#a10334[114]. A timer is cancelled by calling its
_cancel_ method.

Invocations of the timeout callback methods
and the methods of the Timer Service to programmatically create timers
and to cancel timers are typically made within a transaction.

The Timer Service is intended for the
modelling of long-lived business processes. Timers survive container
crashes, server shutdown, and the activation/passivation and load/store
cycles of the enterprise beans that are registered with them. These
persistent guarantees can optionally be disabled on a per-timer basis.

[[a5478]]
==== Calendar-Based Time Expressions

The Timer Service allows a timer callback
schedule to be expressed using a calendar-based syntax that is modeled
after the UNIX cron facility. Calendar-based expressions can be used
both for programmatic timer creation and for automatic timer creation,
and can be specified by means of annotations or the deployment
descriptor. Each of these approaches for expressing the calendar-based
schedule shares common syntax and defaults.

===== Calendar-Based Time Expression Attributes

There are seven attributes in a
calendar-based time expression:

second: one or more seconds within a minute

{empty} Allowable values: [0,59]

minute: one or more minutes within an hour

{empty} Allowable values: [0,59]

hour: one or more hours within a day

{empty} Allowable values: [0,23]

dayOfMonth: one or more days within a month

 Allowable values:

 [1,31] or

 [-7, -1] or

 “Last” or

 \{“1st”, “2nd”, “3rd”, “4th”, “5th”, “Last”}
\{“Sun”, “Mon”, “Tue”, “Wed”, “Thu”, “Fri”, “Sat”}

 “Last” means the last day of the month

 -x (where x is in the range [-7, -1]) means
x day(s) before the last day of the month

 “1st”,”2nd”, etc. applied to a day of the
week identifies a single occurrence of that day within the month.

month: one or more months within a year

 Allowable values:

{empty} [1,12]

 or

 \{“Jan”, “Feb”, “Mar”, ‘’Apr”, “May”, “Jun”,
“Jul”, “Aug”, “Sep”, “Oct”, “Nov”, Dec”}

dayOfWeek: one or more days within a week

 Allowable values:

 [0,7] or

 \{“Sun”, “Mon”, “Tue”, “Wed”, “Thu”, “Fri”,
“Sat”}

 “0” and “7” both refer to Sunday

year: a particular calendar year

 Allowable values: a four-digit calendar year

===== Attribute Syntax

Each attribute supports values expressed in
one of the following forms:

====== Single Value

Use of a single value constrains the
attribute to only one of its possible values.

 _Examples:_

 second = "10"



 month= "Sep"



====== Wild Card

The wild card " _*_ " represents all possible
values for a given attribute.

 _Examples:_

 _second = "*"_

 _dayOfWeek = "*"_

====== List

A list constrains the attribute to two or
more allowable values or ranges, with a comma used as a separator
character and a dash used to indicate an inclusive range. Each item in
the list must be an individual attribute value or a range. List items
cannot themselves be lists, wild-cards, or increments. Duplicate values
are allowed, but are ignored.

 _Examples:_

 _second = "10,20,30"_

 __

 _dayOfWeek = "Mon,Wed,Fri"_



 _minute = "0-10,30,40"_



====== Range

A range constrains the attribute to an
inclusive range of values, with a dash separating both ends of the
range. Each side of the range must be an individual attribute value.
Members of a range cannot themselves be lists, wild-cards, ranges, or
increments. In range "x-y", if _x_ is larger than _y_ , the range is
equivalent to "x-max, min-y", where max is the largest value of the
corresponding attribute and min is the smallest. The range "x-x", where
both range values are the same, is equivalent to the single value x. The
dayOfWeek range "0-7" is equivalent to " _*_ ".

 _Examples:_

 second= "1-10"



 dayOfWeek = "Fri-Mon"



 dayOfMonth = "27-3" (Equivalent to "27-Last,
1-3")



====== Increments

The forward slash constrains an attribute
based on a starting point and an interval, and is used to specify every
N \{ seconds | minutes | hours } within the \{ minute | hour | day }
respectively. For an expression x/y, the attribute is constrained to
every yth value within the set of allowable values beginning at time x.
The x value is inclusive. The wildcard character ( _*_ ) can be used in
the x position, and is equivalent to 0. Increments are only supported
within the second, minute, and hour attributes. For the second and
minute attributes, x and y must each be in the range [0,59]. For the
hour attribute, _x_ and y must each be in the range [0,23].

 _Example:_ _Every five minutes within the
hour_

 minute = "*/5"

The following is equivalent:

 minute = "0,5,10,15,20,25,30,35,40,45,50,55"

 _Example:_ Every 10 seconds within the
minute, starting at second 30

 second = "30/10"

The following is equivalent:

 second = "30,40,50"

Note that the set of matching increment
values stops once the maximum value for that attribute is exceeded. It
does not “roll over” past the boundary.

 _Example:_ _Every 14 minutes within the
hour, for the hours of 1 and 2 a.m._

 (minute = "*/14", hour="1,2")

The following is equivalent:

 ( minute = "0,14,28,42,56", hour = "1,2")



====== Time Zone Support

Calendar-based timer expressions are
evaluated in the context of the default time zone associated with the
container in which the application is executing. A calendar-based timer
may optionally override this default and associate itself with a
specific time zone. If the calendar-based timer is associated with a
specific time zone, all its times are evaluated in the context of that
time zone, regardless of the default time zone in which the container is
executing.

Time zones are specified as an ID
Stringlink:#a10335[115]. The set of required time zone IDs is
defined by the Zone Name(TZ) column of the public domain zoneinfo
database link:Ejb.html#a9885[See List of zoneinfo time zones:
http://en.wikipedia.org/wiki/List_of_tz_zones.].

===== Expression Rules

The second, minute, and hour attributes have
a default value of " _0_ ".

The dayOfMonth, month, dayOfWeek, and year
attributes have a default value of " _*_ ".

If the dayOfMonth attribute has a
non-wildcard value and the dayOfWeek attribute has a non-wildcard value,
then the timer expires when the current day matches either the
dayOfMonth attribute or the dayOfWeek attribute (i.e. the current day
does not need to match of both attributes).

Whitespace is ignored, except for string
constants and numeric values.

All string constants (" _Sun_ ", " _Jan_ ", "
_1st_ ", etc.) are case insensitive.

“5th” is the highest ordinal number allowed
as the value for the dayOfMonth

Duplicate values within attributes using the
list syntax are ignored.

The increments syntax is only supported
within the second, minute, and hour attributes.

===== Examples

These examples illustrate the use of
attribute syntax in conjunction with the _Schedule_ annotation.

====== “Every Monday at Midnight”



 @Schedule(dayOfWeek="Mon")

The following fully-qualified expression is
equivalent:

 @Schedule(second="0", minute="0", hour="0",
dayOfMonth="*", month="*", dayOfWeek="Mon", year="*")



====== “Every Weekday morning at 3:15”



 @Schedule(minute="15", hour="3",
dayOfWeek="Mon-Fri")



====== “Every morning at 3:15 U.S. Eastern Time”



 @Schedule(minute="15", hour="3",
timezone="America/New_York")



====== “Every minute of every hour of every day”



 @Schedule(minute="*", hour="*")



====== “Every Monday, Wednesday, and Friday at 30 seconds past noon”



 @Schedule(second="30", hour="12",
dayOfWeek="Mon,Wed,Fri"



====== “Every five minutes within the hour”



 @Schedule(minute="*/5", hour="*")

The following expression is equivalent:


@Schedule(minute="0,5,10,15,20,25,30,35,40,45,50,55", hour="*")



====== “The last Thursday in November at 2 p.m.”



 @Schedule(hour="14", dayOfMonth="Last Thu",
month="Nov"}



====== “The second to last day (one day before the last day) of each month at 1 a.m.”



 @Schedule(hour="1", dayOfMonth="-1")



====== “Every other hour within the day starting at noon on the 2nd Tuesday of every month.”

 __

 _@Schedule(hour=_ " _12/2_ " _, dayOfMonth=_
" _2nd Tue_ ")

==== Automatic Timer Creation

The Timer Service supports the automatic
creation of timers based on annotations to methods of the bean class or
the deployment descriptor. Automatically created timers are created by
the container as a result of application deployment.

The Schedule annotation can be used to
automatically create a timer with a particular timeout schedule. This
annotation is applied to a method of a bean class (or superclass) that
should receive the timer callbacks associated with that schedule.

 _Example:_

// Generate account statements at 1 a.m. on
the 1st of every month

@Schedule(hour="1", dayOfMonth="1")

public void
generateMonthlyAccountStatements() \{ ... }



Multiple automatic timers can be applied to a
single timeout callback method using the Schedules annotation.

 _Example:_

@Schedules(

\{ @Schedule(hour="12", dayOfWeek="Mon-Thu"),

 @Schedule(hour="11", dayOfWeek="Fri")

})

public void sendLunchNotification() \{ ... }



{empty}A Schedule annotation can optionally
specify an info string. This string can be retrieved by calling
Timer.getInfo() on the associated Timer object. If no info string is
specified, the getInfo() method for a timer created by means of the
Schedule annotation returns null. link:#a10336[116]

 _Example:_

// Generate account statements at 1 a.m. on
the 1st of every month

@Schedule(hour="1", dayOfMonth="1",
info="AccountStatementTimer")

public void
generateMonthlyAccountStatements(Timer t) \{

 String timerInfo = t.getInfo();

 ...

}



By default, each Schedule annotation
corresponds to a single persistent timer, regardless of the number of
JVMs across which the container is distributed.

==== Non-persistent Timers

A non-persistent timer is a timer whose
lifetime is tied to the JVM in which it is created. A non-persistent
timer is considered cancelled in the event of application shutdown,
container crash, or a failure/shutdown of the JVM on which the timer was
started.

Non-persistent timers can be created
programmatically or created automatically using the Schedule annotation
or the deployment descriptor.

Automatically-created non-persistent timers
can be specified by setting the persistent element of the Schedule
annotation to false.

 _Example:_

@Singleton

public class CacheBean \{



 Cache cache;



 // Setup an automatic timer to refresh

 // the Singleton instance cache every 10
minutes

 @Schedule(minute="*/10", hour="*",
persistent=false)

 public void refresh() \{

 // ...

 }



}

==== The TimerService Interface

The _TimerService_ object is accessed via
dependency injection, through the _getTimerService_ method of the
_EJBContext_ interface, or through lookup in the JNDI namespace. The
_TimerService_ interface has the following methods:

public interface javax.ejb.TimerService \{



 public Timer createTimer(long duration,

 java.io.Serializable info);



 public Timer createTimer(java.util.Date
expiration,

 java.io.Serializable info);





 public Timer createSingleActionTimer(long
duration,

 TimerConfig timerConfig);



 public Timer
createSingleActionTimer(java.util.Date expiration,

 TimerConfig timerConfig);





 public Timer createTimer(long
initialDuration,

 long intervalDuration, java.io.Serializable
info);



 public Timer createTimer(java.util.Date
initialExpiration,

 long intervalDuration, java.io.Serializable
info);





 public Timer createIntervalTimer(long
initialDuration,

 long intervalDuration, TimerConfig
timerConfig);



 public Timer createIntervalTimer(

 java.util.Date initialExpiration,

 long intervalDuration, TimerConfig
timerConfig);







 public Timer
createCalendarTimer(ScheduleExpression schedule);



 public Timer
createCalendarTimer(ScheduleExpression schedule,

 TimerConfig timerConfig);





 public Collection<Timer> getTimers();



 public Collection<Timer> getAllTimers();



 }



The timer creation methods allow a timer to
be programmatically created as a single-event timer, as an interval
timer, or as a calendar-based timer.

For single-event timers and interval timers,
the timer expiration (initial expiration in the case of an interval
timer) may be expressed either in terms of a duration or as an absolute
time. The timer duration is expressed in terms of milliseconds. The
Timer Service begins counting down the timer duration upon timer
creation.

For calendar-based timers, the schedule is
expressed by a ScheduleExpression helper object passed as a parameter to
a createCalendarTimer method. The ScheduleExpression object represents a
calendar based timer expression conforming to the requirements in
section link:Ejb.html#a5478[See Calendar-Based Time
Expressions]. The ScheduleExpression class has additional methods that
further constrain the schedule based on an optional start date and/or
end date.

{empty}The bean may pass some client-specific
information at timer creation to help it recognize the significance of a
timer’s expiration. This information is stored by the Timer Service and
available through the timer. The information object must be
serializable. link:#a10337[117]

By default, all timers created using the
timer creation methods are persistent. A non-persistent timer can be
created by calling setPersistent(false) on a TimerConfig object passed
to a timer creation method. The TimerConfig object also supports the
setting of an info object.

The timer creation methods return a _Timer_
object that allows the timer to be cancelled or to obtain information
about the timer prior to its cancellation and/or expiration.

The _getTimers_ method returns active timers
associated with the bean. These include all active persistent timers
regardless of the number of JVMs across which the container is
distributed, and active non-persistent timers created in the same JVM as
the executing method. Timers returned by this method include both the
programmatically-created timers and the automatically-created timers.

The _getAllTimers_ method returns active
timers associated with the beans in the same module in which the caller
bean is packaged. These include all active persistent timers regardless
of the number of JVMs across which the container is distributed, and
active non-persistent timers created in the same JVM as the executing
method. Timers returned by this method include both the
programmatically-created timers and the automatically-created timers.

===== Example

This code programmatically creates a timer
that expires every Saturday at 1 a.m.

ScheduleExpression schedule =

 new
ScheduleExpression().dayOfWeek("Sat").hour(1);

Timer timer =
timerService.createCalendarTimer(schedule);

==== Timeout Callback Methods

The enterprise bean class of a bean that is
to be registered with the Timer Service for timer callbacks must provide
one or more timeout callback methods.

There are two kinds of timeout callback
methods:

timeout callback methods for timers that are
programmatically created via a _TimerService_ timer creation method

timeout callback methods for timers that are
automatically created via the Schedule annotation or the deployment
descriptor

===== Timeout Callbacks for Programmatic Timers

{empty}All timers created via one of the
_TimerService_ timer creation methods for a particular bean must use a
single timeout callback method. This method must either be a single
method annotated with the _Timeout_ annotation (or a method specified as
a timeout method in the deployment descriptor) or the bean must
implement the _javax.ejb.TimedObject_ interface. The _TimedObject_
interface has a single method, _ejbTimeout_ . If the bean implements the
_TimedObject_ interface, the _Timeout_ annotation or _timeout-method_
deployment descriptor element can only be used to specify the
_ejbTimeout_ method. A bean can have at most one timeout method for
handling programmatic timers.link:#a10338[118]

public interface javax.ejb.TimedObject \{

 public void ejbTimeout(Timer timer);

}



===== Timeout Callbacks for Automatically Created Timers

Each automatically-created timer is
associated with a single timeout callback method. Each timeout method is
declared using either the Schedule annotation or the deployment
descriptor. A timed object can have any number of automatically created
timers. The timeout callback method for the programmatically-created
timers can also be associated with the automatically-created timers.

===== Timeout Callback Method Requirements



A timeout callback method must have one of
the two signatures below, where <METHOD> designates the method
namelink:#a10339[119].

void <METHOD>()

{empty}void <METHOD>(Timer
timer)link:#a10340[120]

A timeout callback method can have public,
private, protected, or package level access. A timeout callback method
must not be declared as _final_ or _static_ .

Timeout callback methods must not throw
application exceptions.

When a timer expires (i.e., after one of its
scheduled times arrives or after the absolute time specified has
passed), the container calls the associated timeout method of the bean
that was registered for the timer. The timeout method contains the
business logic that the Bean Provider supplies to handle the timeout
event. The container calls the timeout method with the timer that has
expired. The Bean Provider can use the _getInfo_ method to retrieve the
information that was supplied when the timer was created. This
information may be useful in enabling the timed object to recognize the
significance of the timer expiration.

The container interleaves calls to a timeout
callback method with the calls to the business methods and the life
cycle callback methods of the bean. The time at which a timeout callback
method is called may therefore not correspond exactly to the time
specified at timer creation. If multiple timers have been created for a
bean and will expire at approximately the same times, the Bean Provider
must be prepared to handle timeout callbacks that are out of sequence.
The Bean Provider must be prepared to handle extraneous calls to a
_timeout_ _callback_ method in the event that a timer expiration is
outstanding when a call to the cancellation method has been made.

In general, _a_ timeout callback method can
perform the same operations as business methods from the component
interface or message listener methods. See Tables
link:Ejb.html#a1091[See Operations Allowed in the Methods of a
Stateless Session Bean], link:Ejb.html#a1886[See Operations
Allowed in the Methods of a Message-Driven Bean],
link:../Optional/Chapters.html#UNKNOWN[], and
link:../Optional/Chapters.html#UNKNOWN[] for the specification of the
operations that may be performed by a timeout callback method.

Since a timeout callback method is an
internal method of the bean class, it has no client security context.
When _getCallerPrincipal_ is called from within a timeout callback
method, it returns the container’s representation of the unauthenticated
identity.

If the timed object needs to make use of the
identity of the timer to recognize the significance of the timer
expiration, it may use the _equals_ method to compare it with any other
timer references it might have outstanding.

If the timer is a single-action timer, the
container removes the timer after the timeout callback method has been
successfully invoked (e.g., when the transaction that has been started
for the invocation of the timeout callback method commits). If any
method is invoked on the timer after the termination of the timeout
callback method, a _NoSuchObjectLocalException_ must be thrown.

If the timer is a calendar-based timer, the
container removes the timer after the timeout callback method has been
successfully invoked (e.g., when the transaction that has been started
for the invocation of the timeout callback method commits) and there are
no future timeouts corresponding to the timer’s schedule expression. If
any method is invoked on the timer after it has been removed, the
_NoSuchObjectLocalException_ must be thrown. If the bean invokes the
getNextTimeout or getTimeRemaining method on the timer associated with a
timeout callback while within the timeout callback, and there are no
future timeouts for this calendar-based timer, the
NoMoreTimeoutsException must be thrown.

==== The Timer and TimerHandle Interfaces

The _javax.ejb.Timer_ interface allows the
caller to cancel a timer and to obtain information about the timer.

The _javax.ejb.TimerHandle_ interface allows
the caller to obtain a serializable timer handle that may be persisted.
Timer handles are only available for persistent timers. Since timers are
local objects, a TimerHandle must not be passed through a bean’s remote
business interface, remote interface or web service interface.

The methods of these interfaces are as
follows:

 _public interface javax.ejb.Timer \{_



 _public void cancel();_



 _public long getTimeRemaining();_



 public java.util.Date getNextTimeout();



 public javax.ejb.ScheduleExpression
getSchedule();



 _public javax.ejb.TimerHandle getHandle();_



 public java.io.Serializable getInfo();



 public boolean isPersistent();



 public boolean isCalendarTimer();

 _}_





public interface javax.ejb.TimerHandle
extends java.io.Serializable \{



 public javax.ejb.Timer getTimer();



}



==== Timer Identity

Timer instances must be compared using
Timer.equals(Object obj) method. The _==_ operator should not be used
for “object equality” of the timers.

==== Transactions

An enterprise bean typically creates a timer
within the scope of a transaction. If the transaction is then rolled
back, the timer creation is rolled back.

A timer is typically cancelled within a
transaction. If the transaction is rolled back, the container rescinds
the timer cancellation.

A timeout callback method on a bean with
container-managed transactions must have transaction attribute
_REQUIRED_ or _REQUIRES_NEW_ (or _Required_ or _RequiresNew_ if the
deployment descriptor is used to specify the transaction attribute). If
the container-managed transaction is rolled back, the container retries
the timeout.

Note that the container must start a new
transaction if the _REQUIRED_ _(_ _Required_ _)_ transaction attribute
value is used. This transaction attribute value is allowed so that
specification of a transaction attribute for the timeout callback method
can be defaulted.

The transaction semantics described in this
section apply to both persistent and non-persistent timers.

=== Bean Provider’s Responsibilities



This section defines the Bean Provider’s
responsibilities.

==== Enterprise Bean Class

An enterprise bean that is to be registered
with the Timer Service must have a timeout callback method. The
enterprise bean class may have superclasses and/or superinterfaces. If
the bean class has superclasses, the timeout method may be defined in
the bean class, or in any of its superclasses.

==== TimerHandle

Since the _TimerHandle_ interface extends
_java.io.Serializable_ , a client may serialize the handle. The
serialized handle may be used later to obtain a reference to the timer
identified by the handle. A TimerHandle is intended to be storable in
persistent storage.

A TimerHandle must not be passed as an
argument or result of an enterprise bean’s remote business interface,
remote interface, or web service method.

=== Container’s Responsibilities



This section describes the responsibilities
of the Container Provider to support the EJB Timer Service.

==== TimerService, Timer, and TimerHandle Interfaces

The container must provide the implementation
of the _TimerService_ , _Timer_ , and _TimerHandle_ interfaces.

Timer instances must not be serializable.

The container must implement a timer handle
to be usable over the lifetime of the timer.

The container must provide suitable
implementations of the _Timer_ _equals(Object_ _obj)_ and _hashCode()_
methods.

==== Automatic Timers

The container must create a timer for each
automatic timer specified by means of the Schedule annotation or the
deployment descriptor.

==== Timer Expiration and Timeout Callback Method

The container must call the timeout callback
method after the timed duration or the absolute time specification in
the timer creation method has passed. The container must also call a
timeout callback method if a time matching the timer’s schedule
expression has been reached. The Timer Service must begin to count down
the timer duration upon timer creation. The container must call a
timeout callback method with the expired _Timer_ object, unless the
method is a no-arg timeout callback method.

If container-managed transaction demarcation
is used and the _REQUIRED_ or _REQUIRES_NEW_ transaction attribute is
specified or defaulted ( _Required_ or _RequiresNew_ if the deployment
descriptor is used), the container must begin a new transaction prior to
invoking the timeout callback method. If the transaction fails or is
rolled back, the container must retry the timeout at least once.

If the timer is a single-event timer, the
container must cause the timer to no longer exist. If a javax.ejb.Timer
interface method is subsequently invoked on the timer after the
completion of the timeout callback method, the container must throw the
_javax.ejb.NoSuchObjectLocalException_ .

If the Bean Provider invokes the
_setRollbackOnly_ method from within the timeout callback method, the
container must rollback the transaction in which the timeout callback
method is invoked. This has the effect of rescinding the timer
expiration. The container must retry the timeout after the transaction
rollback.

Timers are persistent objects (unless
explicitly created as non-persistent timers). In the event of a
container crash or container shutdown, any single-event persistent
timers that have expired during the intervening time before container
restart must cause the corresponding timeout callback method to be
invoked upon restart. Any interval persistent timers or schedule based
persistent timers that have expired during the intervening time must
cause the corresponding timeout callback method to be invoked at least
once upon restart.

==== Timer Cancellation

When a timer’s _cancel_ method has been
called, the container must cause the timer to no longer exist. If a
javax.ejb.Timer method is subsequently invoked on the timer, the
container must throw the _javax.ejb.NoSuchObjectLocalException_ .

When the cancel method of an automatically
created non-persistent timer has been called, the container only causes
the timer in the currently running JVM to no longer exist. The container
does not nullify the rule that creates a new non-persistent timer upon
application startup.

If the transaction in which the timer
cancellation occurs is rolled back, the container must restore the
duration of the timer to the duration it would have had if it had not
been cancelled. If the timer would have expired by the time that the
transaction failed, the failure of the transaction should result in the
expired timer providing an expiration notification after the transaction
rolls back.
